use byui_degrees;

insert into courses (subject, number, title, credits) values
(
    ("ACCTG", "100", "Introduction to Accounting", 2), 
	("ACCTG", "180", "Survey of Accounting", 3), 
	("ACCTG", "201", "Financial Accounting", 3), 
	("ACCTG", "201", "Financial Accounting", 3), 
	("ACCTG", "201", "Financial Accounting", 3), 
	("ACCTG", "201", "Financial Accounting", 3), 
	("ACCTG", "201", "Financial Accounting", 3), 
	("ACCTG", "201", "Financial Accounting", 3), 
	("ACCTG", "201", "Financial Accounting", 3), 
	("ACCTG", "201", "Financial Accounting", 3), 
	("ACCTG", "201", "Financial Accounting", 3), 
	("ACCTG", "201", "Financial Accounting", 3), 
	("ACCTG", "202", "Managerial Accounting", 3), 
	("ACCTG", "202", "Managerial Accounting", 3), 
	("ACCTG", "202", "Managerial Accounting", 3), 
	("ACCTG", "202", "Managerial Accounting", 3), 
	("ACCTG", "202", "Managerial Accounting", 3), 
	("ACCTG", "205", "Accounting Software", 2), 
	("ACCTG", "233", "Spreadsheet Application", 1), 
	("ACCTG", "233", "Spreadsheet Application", 1), 
	("ACCTG", "233", "Spreadsheet Application", 1), 
	("ACCTG", "275", "Accounting Exploration", 1), 
	("AGTEC", "186", "Intro to Precision Ag", 2), 
	("AGTEC", "220", "Agricultural Safety", 3), 
	("ANTH", "101", "Intro Cultural Anthropology", 3), 
	("APD", "221", "Home Decor Design", 2), 
	("APD", "221", "Home Decor Design", 2), 
	("APD", "235", "Children's Apparel Design", 2), 
	("APD", "245", "Pattern Making", 3), 
	("APD", "290", "CAD Pattern Making", 2), 
	("APS", "103", "Home Gardening", 3), 
	("APS", "103", "Home Gardening", 3), 
	("APS", "122", "Intro to Plant Science", 3), 
	("APS", "123", "Intro to Plant Science Lab", 1), 
	("APS", "220", "Horticultural Soils", 3), 
	("APS", "220L", "Soils Lab", 1), 
	("APS", "220L", "Soils Lab", 1), 
	("APS", "290R", "Special Problems", 1), 
	("APS", "290R", "Special Problems", 1), 
	("APS", "299R", "Seminar", 1), 
	("ART", "101", "Intro to the Visual Arts", 3), 
	("ART", "106", "Freshman Art Orient Seminar", 0.5), 
	("ART", "107", "Design and Color", 3), 
	("ART", "110", "Drawing I", 3), 
	("ART", "110", "Drawing I", 3), 
	("ART", "110", "Drawing I", 3), 
	("ART", "110", "Drawing I", 3), 
	("ART", "110", "Drawing I", 3), 
	("ART", "110", "Drawing I", 3), 
	("ART", "130", "Intro to Graphic Design", 3), 
	("ART", "142", "Media Experimentation", 3), 
	("ART", "160", "Photography I", 3), 
	("ART", "160", "Photography I", 3), 
	("ART", "201", "Art History I", 3), 
	("ART", "201", "Art History I", 3), 
	("ART", "201", "Art History I", 3), 
	("ART", "202", "Art History II", 3), 
	("ART", "202", "Art History II", 3), 
	("ART", "202", "Art History II", 3), 
	("ART", "202", "Art History II", 3), 
	("ART", "210", "Drawing II", 3), 
	("ART", "210", "Drawing II", 3), 
	("ART", "217", "Design and Color II", 3), 
	("ART", "220", "Ceramics I", 3), 
	("ART", "220", "Ceramics I", 3), 
	("ART", "220", "Ceramics I", 3), 
	("ART", "230", "Typography I", 3), 
	("ART", "231", "Inquiry & Innovation", 3), 
	("ART", "231", "Inquiry & Innovation", 3), 
	("ART", "235", "Graphic Design", 3), 
	("ART", "235", "Graphic Design", 3), 
	("ART", "240", "Introduction to Illustration", 3), 
	("ART", "240L", "Illustration Portfolio Lab", 0.5), 
	("ART", "245R", "2D Digital Illustration", 3), 
	("ART", "248R", "Character Animation I", 3), 
	("ART", "250", "Oil Painting I", 3), 
	("ART", "250", "Oil Painting I", 3), 
	("ART", "251R", "Watercolor", 3), 
	("ART", "251R", "Watercolor", 3), 
	("ART", "260", "Intermediate Photography", 3), 
	("ART", "270", "Printmaking I", 3), 
	("ART", "270", "Printmaking I", 3), 
	("ART", "280", "Sculpture I", 3), 
	("ART", "280", "Sculpture I", 3), 
	("ART", "297R", "Art Seminar", 0.5), 
	("AS", "125", "Career Exploration in AS", 1), 
	("AS", "135", "Intro to Meat Products", 1), 
	("AS", "135", "Intro to Meat Products", 1), 
	("AS", "150", "Intro to Animal Science", 3), 
	("AS", "150", "Intro to Animal Science", 3), 
	("AS", "215", "Animal Anatomy & Physiology", 3), 
	("AS", "215", "Animal Anatomy & Physiology", 3), 
	("AS", "215L", "Animal Anatomy & Phys Lab", 1), 
	("AS", "215L", "Animal Anatomy & Phys Lab", 1), 
	("AS", "215L", "Animal Anatomy & Phys Lab", 1), 
	("AS", "220", "Feeds and Nutrition", 3), 
	("AS", "234", "Veterinary Parasitology", 2), 
	("AS", "247", "Animal Handling and Behavior", 3), 
	("AS", "247", "Animal Handling and Behavior", 3), 
	("AS", "247", "Animal Handling and Behavior", 3), 
	("AUTO", "125", "Auto Ownership & Maintenance", 1), 
	("AUTO", "125", "Auto Ownership & Maintenance", 1), 
	("AUTO", "125", "Auto Ownership & Maintenance", 1), 
	("AUTO", "125", "Auto Ownership & Maintenance", 1), 
	("AUTO", "125", "Auto Ownership & Maintenance", 1), 
	("AUTO", "125", "Auto Ownership & Maintenance", 1), 
	("AUTO", "125", "Auto Ownership & Maintenance", 1), 
	("AUTO", "131", "Electrical Systems", 2), 
	("AUTO", "131", "Electrical Systems", 2), 
	("AUTO", "131L", "Electrical Systems Lab", 1), 
	("AUTO", "131L", "Electrical Systems Lab", 1), 
	("AUTO", "131L", "Electrical Systems Lab", 1), 
	("AUTO", "132", "Engine Performance", 2), 
	("AUTO", "132", "Engine Performance", 2), 
	("AUTO", "132L", "Engine Performance Lab", 1), 
	("AUTO", "132L", "Engine Performance Lab", 1), 
	("AUTO", "132L", "Engine Performance Lab", 1), 
	("AUTO", "200", "Career Planning & Networking", 3), 
	("AUTO", "223", "Climate Control", 2), 
	("AUTO", "223L", "Climate Control Lab", 1), 
	("AUTO", "255", "Braking Systems", 2), 
	("AUTO", "255L", "Braking Systems Lab", 1), 
	("AUTO", "255L", "Braking Systems Lab", 1), 
	("AUTO", "256", "Chassis Dynamics", 2), 
	("AUTO", "256L", "Chassis Dynamics Lab", 1), 
	("AUTO", "256L", "Chassis Dynamics Lab", 1), 
	("BA", "211", "Business Fundamentals", 3), 
	("BA", "211", "Business Fundamentals", 3), 
	("BA", "211", "Business Fundamentals", 3), 
	("BA", "211", "Business Fundamentals", 3), 
	("BA", "211", "Business Fundamentals", 3), 
	("BA", "211", "Business Fundamentals", 3), 
	("BA", "211", "Business Fundamentals", 3), 
	("BA", "215", "Spreadsheet Analysis for Bus", 3), 
	("BA", "215", "Spreadsheet Analysis for Bus", 3), 
	("BA", "215", "Spreadsheet Analysis for Bus", 3), 
	("BA", "215", "Spreadsheet Analysis for Bus", 3), 
	("BA", "215", "Spreadsheet Analysis for Bus", 3), 
	("BA", "215", "Spreadsheet Analysis for Bus", 3), 
	("BA", "215", "Spreadsheet Analysis for Bus", 3), 
	("BIO", "101", "Intro Bio Allied Health", 3), 
	("BIO", "180", "Introduction to Biology I", 3), 
	("BIO", "180", "Introduction to Biology I", 3), 
	("BIO", "180", "Introduction to Biology I", 3), 
	("BIO", "180", "Introduction to Biology I", 3), 
	("BIO", "180", "Introduction to Biology I", 3), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "180L", "Intro to Biology I Lab", 1), 
	("BIO", "181", "Introduction to Biology II", 3), 
	("BIO", "181", "Introduction to Biology II", 3), 
	("BIO", "181", "Introduction to Biology II", 3), 
	("BIO", "181L", "Intro to Biology II Lab", 1), 
	("BIO", "181L", "Intro to Biology II Lab", 1), 
	("BIO", "181L", "Intro to Biology II Lab", 1), 
	("BIO", "181L", "Intro to Biology II Lab", 1), 
	("BIO", "181L", "Intro to Biology II Lab", 1), 
	("BIO", "181L", "Intro to Biology II Lab", 1), 
	("BIO", "181L", "Intro to Biology II Lab", 1), 
	("BIO", "181L", "Intro to Biology II Lab", 1), 
	("BIO", "181L", "Intro to Biology II Lab", 1), 
	("BIO", "182", "Introduction to Biology III", 4), 
	("BIO", "198", "Wildlife Nat Resource Orien", 1), 
	("BIO", "199", "Biology Orientation", 1), 
	("BIO", "199", "Biology Orientation", 1), 
	("BIO", "199", "Biology Orientation", 1), 
	("BIO", "199", "Biology Orientation", 1), 
	("BIO", "203", "Basic Skills and Safety", 1), 
	("BIO", "208", "Intro to Plant Biology", 4), 
	("BIO", "221", "General Microbiology", 3), 
	("BIO", "221", "General Microbiology", 3), 
	("BIO", "221", "General Microbiology", 3), 
	("BIO", "222", "General Microbiology Lab", 1), 
	("BIO", "222", "General Microbiology Lab", 1), 
	("BIO", "222", "General Microbiology Lab", 1), 
	("BIO", "222", "General Microbiology Lab", 1), 
	("BIO", "222", "General Microbiology Lab", 1), 
	("BIO", "222", "General Microbiology Lab", 1), 
	("BIO", "222", "General Microbiology Lab", 1), 
	("BIO", "225", "Range Management", 3), 
	("BIO", "230", "Essential Human Anat & Phys", 4), 
	("BIO", "230", "Essential Human Anat & Phys", 4), 
	("BIO", "230", "Essential Human Anat & Phys", 4), 
	("BIO", "240", "Neurobiology", 4), 
	("BIO", "250", "Environmental Biology w/Lab", 4), 
	("BIO", "264", "Human Anat & Physiology I", 3), 
	("BIO", "264", "Human Anat & Physiology I", 3), 
	("BIO", "264", "Human Anat & Physiology I", 3), 
	("BIO", "264", "Human Anat & Physiology I", 3), 
	("BIO", "264", "Human Anat & Physiology I", 3), 
	("BIO", "264", "Human Anat & Physiology I", 3), 
	("BIO", "264L", "Human Anat Physiology I Lab", 1), 
	("BIO", "264L", "Human Anat Physiology I Lab", 1), 
	("BIO", "264L", "Human Anat Physiology I Lab", 1), 
	("BIO", "264L", "Human Anat Physiology I Lab", 1), 
	("BIO", "264L", "Human Anat Physiology I Lab", 1), 
	("BIO", "264L", "Human Anat Physiology I Lab", 1), 
	("BIO", "264L", "Human Anat Physiology I Lab", 1), 
	("BIO", "264L", "Human Anat Physiology I Lab", 1), 
	("BIO", "264L", "Human Anat Physiology I Lab", 1), 
	("BIO", "264L", "Human Anat Physiology I Lab", 1), 
	("BIO", "265", "Human Anat & Physiology II", 3), 
	("BIO", "265", "Human Anat & Physiology II", 3), 
	("BIO", "265", "Human Anat & Physiology II", 3), 
	("BIO", "265L", "Human Anat & Phys II Lab", 1), 
	("BIO", "265L", "Human Anat & Phys II Lab", 1), 
	("BIO", "265L", "Human Anat & Phys II Lab", 1), 
	("BIO", "265L", "Human Anat & Phys II Lab", 1), 
	("BIO", "265L", "Human Anat & Phys II Lab", 1), 
	("BIO", "265L", "Human Anat & Phys II Lab", 1), 
	("BIO", "265L", "Human Anat & Phys II Lab", 1), 
	("BIO", "265L", "Human Anat & Phys II Lab", 1), 
	("BIO", "265L", "Human Anat & Phys II Lab", 1), 
	("BIO", "265L", "Human Anat & Phys II Lab", 1), 
	("BUS", "100", "Bus. Exploration/Orientation", 1), 
	("BUS", "100", "Bus. Exploration/Orientation", 1), 
	("BUS", "100", "Bus. Exploration/Orientation", 1), 
	("BUS", "101", "Introduction to Business", 3), 
	("BUS", "101", "Introduction to Business", 3), 
	("BUS", "101", "Introduction to Business", 3), 
	("BUS", "200", "Small Business Management", 3), 
	("BUS", "200", "Small Business Management", 3), 
	("BUS", "200", "Small Business Management", 3), 
	("BUS", "200", "Small Business Management", 3), 
	("BUS", "200", "Small Business Management", 3), 
	("BUS", "200", "Small Business Management", 3), 
	("BUS", "200", "Small Business Management", 3), 
	("BUS", "200", "Small Business Management", 3), 
	("BUS", "200", "Small Business Management", 3), 
	("BUS", "270", "Human Resource Management", 3), 
	("CE", "250", "Civil Eng. Materials Science", 3), 
	("CHEM", "101", "Introductory Chemistry", 3), 
	("CHEM", "101", "Introductory Chemistry", 3), 
	("CHEM", "101", "Introductory Chemistry", 3), 
	("CHEM", "101", "Introductory Chemistry", 3), 
	("CHEM", "101", "Introductory Chemistry", 3), 
	("CHEM", "101L", "Introductory Chemistry Lab", 1), 
	("CHEM", "101L", "Introductory Chemistry Lab", 1), 
	("CHEM", "101L", "Introductory Chemistry Lab", 1), 
	("CHEM", "101L", "Introductory Chemistry Lab", 1), 
	("CHEM", "101L", "Introductory Chemistry Lab", 1), 
	("CHEM", "105", "General Chemistry I", 3), 
	("CHEM", "105", "General Chemistry I", 3), 
	("CHEM", "105", "General Chemistry I", 3), 
	("CHEM", "105", "General Chemistry I", 3), 
	("CHEM", "105", "General Chemistry I", 3), 
	("CHEM", "105", "General Chemistry I", 3), 
	("CHEM", "105", "General Chemistry I", 3), 
	("CHEM", "105", "General Chemistry I", 3), 
	("CHEM", "105L", "General Chemistry Lab I", 1), 
	("CHEM", "105L", "General Chemistry Lab I", 1), 
	("CHEM", "105L", "General Chemistry Lab I", 1), 
	("CHEM", "105L", "General Chemistry Lab I", 1), 
	("CHEM", "105L", "General Chemistry Lab I", 1), 
	("CHEM", "105L", "General Chemistry Lab I", 1), 
	("CHEM", "106", "General Chemistry II", 3), 
	("CHEM", "106", "General Chemistry II", 3), 
	("CHEM", "106", "General Chemistry II", 3), 
	("CHEM", "106", "General Chemistry II", 3), 
	("CHEM", "106L", "General Chemistry Lab II", 1), 
	("CHEM", "106L", "General Chemistry Lab II", 1), 
	("CHEM", "106L", "General Chemistry Lab II", 1), 
	("CHEM", "106L", "General Chemistry Lab II", 1), 
	("CHEM", "220", "Quantitative Analysis", 3), 
	("CHEM", "220L", "Quantitative Analysis Lab", 2), 
	("CHEM", "220L", "Quantitative Analysis Lab", 2), 
	("CHEM", "290R", "Special Topics in Chemistry", 1), 
	("CHILD", "120", "Infants and Toddlers", 1), 
	("CHILD", "120", "Infants and Toddlers", 1), 
	("CHILD", "150", "Foundations Early Child", 3), 
	("CHILD", "150", "Foundations Early Child", 3), 
	("CHILD", "210", "Child Development", 3), 
	("CHILD", "210", "Child Development", 3), 
	("CHILD", "210", "Child Development", 3), 
	("CHILD", "210", "Child Development", 3), 
	("CHILD", "210", "Child Development", 3), 
	("CHILD", "210", "Child Development", 3), 
	("CHILD", "210", "Child Development", 3), 
	("CHILD", "230", "Curriculum Young Children", 3), 
	("CHILD", "232", "Language and Literacy", 2), 
	("CHILD", "234", "Fostering Devel Nat Settings", 2), 
	("CHILD", "234", "Fostering Devel Nat Settings", 2), 
	("CHIN", "101", "Beginning Mandarin I", 4), 
	("CHIN", "101", "Beginning Mandarin I", 4), 
	("CHIN", "102", "Beginning Mandarin II", 4), 
	("CHIN", "202", "Intermediate Mandarin II", 4), 
	("CIVIC", "150", "Citizenship & Const. Gov.", 3), 
	("CIVIC", "150", "Citizenship & Const. Gov.", 3), 
	("CIVIC", "150", "Citizenship & Const. Gov.", 3), 
	("COMM", "100", "Intro to Communication", 1), 
	("COMM", "102", "Public Speaking", 3), 
	("COMM", "102", "Public Speaking", 3), 
	("COMM", "102", "Public Speaking", 3), 
	("COMM", "102", "Public Speaking", 3), 
	("COMM", "102", "Public Speaking", 3), 
	("COMM", "102", "Public Speaking", 3), 
	("COMM", "102", "Public Speaking", 3), 
	("COMM", "102", "Public Speaking", 3), 
	("COMM", "111", "Writing for Comm Career", 3), 
	("COMM", "111", "Writing for Comm Career", 3), 
	("COMM", "130", "Visual Media", 3), 
	("COMM", "130", "Visual Media", 3), 
	("COMM", "130", "Visual Media", 3), 
	("COMM", "140", "Mass Media and Society", 3), 
	("COMM", "140", "Mass Media and Society", 3), 
	("COMM", "150", "Interpersonal Theory & Pract", 3), 
	("COMM", "150", "Interpersonal Theory & Pract", 3), 
	("COMM", "150", "Interpersonal Theory & Pract", 3), 
	("COMM", "150", "Interpersonal Theory & Pract", 3), 
	("COMM", "222", "Digital Branding", 3), 
	("COMM", "222", "Digital Branding", 3), 
	("COMM", "235", "PR Principles and Writing", 3), 
	("COMM", "240", "Newsgathering Prin & Prac", 3), 
	("COMM", "250", "Organizational Principles", 3), 
	("COMM", "250", "Organizational Principles", 3), 
	("COMM", "260", "Video Principles & Practices", 3), 
	("COMM", "265", "Video & Film Prod Essentials", 3), 
	("COMM", "265", "Video & Film Prod Essentials", 3), 
	("COMM", "273", "Professional Presentations", 3), 
	("COMM", "273", "Professional Presentations", 3), 
	("COMM", "280", "Comm Research Fundamentals", 3), 
	("COMM", "297R", "Communication Practicum I", 1), 
	("CONST", "100", "Basic Woodworking", 3), 
	("CONST", "105", "Survey of VDC and CM", 1), 
	("CONST", "105", "Survey of VDC and CM", 1), 
	("CONST", "120", "Framing Systems", 3), 
	("CONST", "120", "Framing Systems", 3), 
	("CONST", "120", "Framing Systems", 3), 
	("CONST", "210", "Finishing Systems", 3), 
	("CONST", "235", "Building Systems", 4), 
	("CONST", "235", "Building Systems", 4), 
	("CONST", "260", "Statics & Strength Materials", 3), 
	("CONST", "260", "Statics & Strength Materials", 3), 
	("CSE", "110", "Intro to Programming", 2), 
	("CSE", "110", "Intro to Programming", 2), 
	("CSE", "110", "Intro to Programming", 2), 
	("CSE", "110", "Intro to Programming", 2), 
	("CSE", "110", "Intro to Programming", 2), 
	("CSE", "110", "Intro to Programming", 2), 
	("CSE", "110", "Intro to Programming", 2), 
	("CSE", "110", "Intro to Programming", 2), 
	("CSE", "111", "Programming with Functions", 2), 
	("CSE", "111", "Programming with Functions", 2), 
	("CSE", "111", "Programming with Functions", 2), 
	("CSE", "111", "Programming with Functions", 2), 
	("CSE", "111", "Programming with Functions", 2), 
	("CSE", "111", "Programming with Functions", 2), 
	("CSE", "121C", "C Language", 1), 
	("CSE", "121C", "C Language", 1), 
	("CSE", "130", "Algorithm Design", 2), 
	("CSE", "131", "Modularization Design", 2), 
	("CSE", "170", "Technical Teamwork", 2), 
	("CSE", "170", "Technical Teamwork", 2), 
	("CSE", "170", "Technical Teamwork", 2), 
	("CSE", "199R", "Freshman Discovery Project", 1), 
	("CSE", "199R", "Freshman Discovery Project", 1), 
	("CSE", "199R", "Freshman Discovery Project", 1), 
	("CSE", "199R", "Freshman Discovery Project", 1), 
	("CSE", "210", "Programming with Classes", 2), 
	("CSE", "210", "Programming with Classes", 2), 
	("CSE", "210", "Programming with Classes", 2), 
	("CSE", "210", "Programming with Classes", 2), 
	("CSE", "210", "Programming with Classes", 2), 
	("CSE", "212", "Programming w/Data Struct", 2), 
	("CSE", "212", "Programming w/Data Struct", 2), 
	("CSE", "212", "Programming w/Data Struct", 2), 
	("CSE", "230", "Encapsulation Design", 3), 
	("CSE", "231", "Inheritance Design", 2), 
	("CSE", "270", "Software Testing", 3), 
	("CSE", "280", "Discrete Mathematics", 3), 
	("CSE", "280", "Discrete Mathematics", 3), 
	("CYBER", "201", "Cybersecurity Fundamentals", 2), 
	("CYBER", "201", "Cybersecurity Fundamentals", 2), 
	("CYBER", "201", "Cybersecurity Fundamentals", 2), 
	("CYBER", "201", "Cybersecurity Fundamentals", 2), 
	("CYBER", "201", "Cybersecurity Fundamentals", 2), 
	("CYBER", "240", "Networking", 3), 
	("DANCE", "131", "Jazz Dance, Beginning", 1), 
	("DANCE", "131", "Jazz Dance, Beginning", 1), 
	("DANCE", "135", "Tap Dance, Beginning", 1), 
	("DANCE", "135", "Tap Dance, Beginning", 1), 
	("DANCE", "140", "Modern Dance, Beginning", 1), 
	("DANCE", "140", "Modern Dance, Beginning", 1), 
	("DANCE", "170", "World Dance, Beginning", 1), 
	("DANCE", "170", "World Dance, Beginning", 1), 
	("DANCE", "171", "Clog Dance, Beginning", 1), 
	("DANCE", "180M", "Social Dance, Beginning", 1), 
	("DANCE", "180M", "Social Dance, Beginning", 1), 
	("DANCE", "180M", "Social Dance, Beginning", 1), 
	("DANCE", "180M", "Social Dance, Beginning", 1), 
	("DANCE", "180M", "Social Dance, Beginning", 1), 
	("DANCE", "180M", "Social Dance, Beginning", 1), 
	("DANCE", "180M", "Social Dance, Beginning", 1), 
	("DANCE", "180M", "Social Dance, Beginning", 1), 
	("DANCE", "180M", "Social Dance, Beginning", 1), 
	("DANCE", "180M", "Social Dance, Beginning", 1), 
	("DANCE", "180W", "Social Dance, Beginning", 1), 
	("DANCE", "180W", "Social Dance, Beginning", 1), 
	("DANCE", "180W", "Social Dance, Beginning", 1), 
	("DANCE", "180W", "Social Dance, Beginning", 1), 
	("DANCE", "180W", "Social Dance, Beginning", 1), 
	("DANCE", "180W", "Social Dance, Beginning", 1), 
	("DANCE", "180W", "Social Dance, Beginning", 1), 
	("DANCE", "180W", "Social Dance, Beginning", 1), 
	("DANCE", "180W", "Social Dance, Beginning", 1), 
	("DANCE", "180W", "Social Dance, Beginning", 1), 
	("DANCE", "190", "Ballet, Beginning", 1), 
	("DANCE", "190", "Ballet, Beginning", 1), 
	("DANCE", "231R", "Jazz Dance Intermediate", 1), 
	("DANCE", "235R", "Tap Dance Technique", 1), 
	("DANCE", "240R", "Modern Dance Technique I", 2), 
	("DANCE", "242", "Intro Choreographic Devices", 2), 
	("DANCE", "270R", "World Dance Technique 1", 1), 
	("DANCE", "271R", "Clog Dance Technique I", 1), 
	("DANCE", "280R", "Ballroom Technique I", 1), 
	("DANCE", "290R", "Ballet Technique I", 1), 
	("DANCE", "295", "Dance Kinesiology I", 3), 
	("DS", "150", "Data Intuition and Insight", 2), 
	("DS", "150", "Data Intuition and Insight", 2), 
	("DS", "250", "Data Science Programming", 2), 
	("DS", "250", "Data Science Programming", 2), 
	("DS", "250", "Data Science Programming", 2), 
	("DS", "250", "Data Science Programming", 2), 
	("ECEN", "101", "Intro to ECEN", 1), 
	("ECEN", "101", "Intro to ECEN", 1), 
	("ECEN", "106", "Computer Systems", 2), 
	("ECEN", "106", "Computer Systems", 2), 
	("ECEN", "106", "Computer Systems", 2), 
	("ECEN", "150", "Electric Circuit Analysis I", 3), 
	("ECEN", "150", "Electric Circuit Analysis I", 3), 
	("ECEN", "240", "Fundamentals Digital Systems", 3), 
	("ECEN", "240", "Fundamentals Digital Systems", 3), 
	("ECEN", "250", "Electric Circuit Analysis II", 3), 
	("ECEN", "250", "Electric Circuit Analysis II", 3), 
	("ECEN", "260", "Microproc Based-Sys Design", 3), 
	("ECEN", "299", "Elect Circuit Fab & Eval Lab", 1), 
	("ECON", "150", "Econ Principles & Prob Micro", 3), 
	("ECON", "150", "Econ Principles & Prob Micro", 3), 
	("ECON", "150", "Econ Principles & Prob Micro", 3), 
	("ECON", "150", "Econ Principles & Prob Micro", 3), 
	("ECON", "150", "Econ Principles & Prob Micro", 3), 
	("ECON", "150", "Econ Principles & Prob Micro", 3), 
	("ECON", "150", "Econ Principles & Prob Micro", 3), 
	("ECON", "150", "Econ Principles & Prob Micro", 3), 
	("ECON", "151", "Econ Principles & Prob Macro", 3), 
	("ECON", "151", "Econ Principles & Prob Macro", 3), 
	("ECON", "151", "Econ Principles & Prob Macro", 3), 
	("ECON", "151", "Econ Principles & Prob Macro", 3), 
	("ECON", "151", "Econ Principles & Prob Macro", 3), 
	("ECON", "201", "Prof. Exploration & Orient", 1), 
	("ECON", "255", "Financial Analytics", 3), 
	("ED", "246", "ELED Motivation/Class Ldrshp", 2), 
	("ED", "246", "ELED Motivation/Class Ldrshp", 2), 
	("EDCOR", "200", "Teaching as a Profession", 2), 
	("EDCOR", "200", "Teaching as a Profession", 2), 
	("EDCOR", "200", "Teaching as a Profession", 2), 
	("EDCOR", "200", "Teaching as a Profession", 2), 
	("EDCOR", "200", "Teaching as a Profession", 2), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "106", "Basic Writing", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150", "Writing/Reasoning Foundation", 3), 
	("ENG", "150P", "Writing/Reasoning w/Support", 4), 
	("ENG", "151", "Introduction to Literature", 3), 
	("ENG", "151", "Introduction to Literature", 3), 
	("ENG", "151", "Introduction to Literature", 3), 
	("ENG", "217", "Great Books of the World", 3), 
	("ENG", "217", "Great Books of the World", 3), 
	("ENG", "217", "Great Books of the World", 3), 
	("ENG", "218", "Creative Writing", 3), 
	("ENG", "218", "Creative Writing", 3), 
	("ENG", "218", "Creative Writing", 3), 
	("ENG", "218", "Creative Writing", 3), 
	("ENG", "251", "Fund Literary Interpretation", 3), 
	("ENG", "251", "Fund Literary Interpretation", 3), 
	("ENG", "251", "Fund Literary Interpretation", 3), 
	("ENG", "252", "Rhetoric-Design-Professions", 3), 
	("ENG", "252", "Rhetoric-Design-Professions", 3), 
	("ESS", "111", "Exercise Science Orientation", 2), 
	("ESS", "111", "Exercise Science Orientation", 2), 
	("ESS", "115", "Military Physical Fitness", 1), 
	("ESS", "115", "Military Physical Fitness", 1), 
	("ESS", "130", "Body Weight Management", 1), 
	("ESS", "130", "Body Weight Management", 1), 
	("ESS", "178", "Weight Training", 1), 
	("ESS", "178", "Weight Training", 1), 
	("ESS", "204", "Aerobic Fitness Techniques", 2), 
	("ESS", "204", "Aerobic Fitness Techniques", 2), 
	("ESS", "205", "Intramurals", 2), 
	("ESS", "213", "Outdoor Sports Officiating", 2), 
	("ESS", "264", "Lifeguarding", 3), 
	("FAML", "100", "The Family", 3), 
	("FAML", "100", "The Family", 3), 
	("FAML", "120", "Parenting Skills", 1), 
	("FAML", "120", "Parenting Skills", 1), 
	("FAML", "150", "Intro Marriage & Fam Studies", 1), 
	("FAML", "160", "Family Relations", 3), 
	("FAML", "160", "Family Relations", 3), 
	("FAML", "160", "Family Relations", 3), 
	("FAML", "160", "Family Relations", 3), 
	("FAML", "200", "Preparation for Marriage", 2), 
	("FAML", "200", "Preparation for Marriage", 2), 
	("FAML", "220", "Parenting", 3), 
	("FCS", "101", "Intro Family & Consumer Sci", 2), 
	("FCS", "140", "Intro to Interior Design", 3), 
	("FCS", "140", "Intro to Interior Design", 3), 
	("FCS", "160", "Family Leadership & Mgmt.", 3), 
	("FCS", "207", "Apparel Construction I", 2), 
	("FCS", "207", "Apparel Construction I", 2), 
	("FCS", "207", "Apparel Construction I", 2), 
	("FCS", "208", "Fashion Design", 2), 
	("FCS", "240", "Food Preparation", 2), 
	("FCS", "240", "Food Preparation", 2), 
	("FCS", "240", "Food Preparation", 2), 
	("FCS", "240", "Food Preparation", 2), 
	("FCS", "240", "Food Preparation", 2), 
	("FCS", "280", "History of Arch. & Interiors", 3), 
	("FIN", "100", "Intro to Finance", 1), 
	("FIN", "100", "Intro to Finance", 1), 
	("FR", "101", "Beginning French I", 4), 
	("FR", "101", "Beginning French I", 4), 
	("FR", "101", "Beginning French I", 4), 
	("FR", "102", "Beginning French II", 4), 
	("FR", "201", "Intermediate French", 4), 
	("FS", "120", "Introduction to Food Science", 3), 
	("FS", "180", "Survey of Food Science", 1), 
	("FS", "220", "Food Laws and Regulations", 2), 
	("FS", "230", "Intro to Food Preservation", 1), 
	("FS", "260", "Flavor and Menu Design", 3), 
	("GE", "101", "Growth & Grit", 1), 
	("GE", "101", "Growth & Grit", 1), 
	("GE", "101", "Growth & Grit", 1), 
	("GE", "102", "Academic/Emotion Well-Being", 1), 
	("GE", "102", "Academic/Emotion Well-Being", 1), 
	("GE", "105", "Study and Life Skills", 2), 
	("GE", "105", "Study and Life Skills", 2), 
	("GE", "105", "Study and Life Skills", 2), 
	("GE", "105", "Study and Life Skills", 2), 
	("GE", "105", "Study and Life Skills", 2), 
	("GE", "105", "Study and Life Skills", 2), 
	("GECIV", "100", "American Heritage", 3), 
	("GECIV", "105", "Foundations of World History", 3), 
	("GECIV", "105", "Foundations of World History", 3), 
	("GECIV", "105", "Foundations of World History", 3), 
	("GECIV", "210", "Religious Freedom", 3), 
	("GEOG", "101", "Intro Physical Geography", 3), 
	("GEOG", "101L", "Physical Geography Lab", 1), 
	("GEOG", "110", "Geography for Elementary Ed", 3), 
	("GEOG", "120", "Geography and World Affairs", 3), 
	("GEOL", "109", "Introduction to Geology", 3), 
	("GEOL", "111", "Physical Geology", 3), 
	("GEOL", "111L", "Physical Geology Lab", 1), 
	("GESCI", "101", "From Atoms to Humans", 3), 
	("GESCI", "101", "From Atoms to Humans", 3), 
	("GESCI", "101", "From Atoms to Humans", 3), 
	("GESCI", "101", "From Atoms to Humans", 3), 
	("GESCI", "110", "Sustaining Human Life", 3), 
	("GESCI", "110", "Sustaining Human Life", 3), 
	("GESCI", "110", "Sustaining Human Life", 3), 
	("GESCI", "110", "Sustaining Human Life", 3), 
	("GESCI", "110", "Sustaining Human Life", 3), 
	("GESCI", "110", "Sustaining Human Life", 3), 
	("GESCI", "201", "Natural Disasters", 3), 
	("GESCI", "201", "Natural Disasters", 3), 
	("GESCI", "203", "Environmental Stewardship", 3), 
	("GESCI", "204", "The American Epidemic", 3), 
	("GESCI", "205", "DNA: Identity/Disease/Design", 3), 
	("GESCI", "205", "DNA: Identity/Disease/Design", 3), 
	("GESCI", "206", "Light and Sound", 3), 
	("GESCI", "206", "Light and Sound", 3), 
	("GESCI", "208", "Introduction to Robotics", 3), 
	("GESCI", "208", "Introduction to Robotics", 3), 
	("GESCI", "210", "Neanderthals/Other Successes", 3), 
	("GIS", "150", "Spatial Thinking", 1), 
	("GIS", "150", "Spatial Thinking", 1), 
	("GIS", "255", "UAS-Based Mapping", 2), 
	("GREEK", "101", "Ancient Greek I", 4), 
	("GS", "100", "Career and Self Discovery", 1), 
	("GS", "100", "Career and Self Discovery", 1), 
	("GS", "100", "Career and Self Discovery", 1), 
	("GS", "100", "Career and Self Discovery", 1), 
	("GS", "100", "Career and Self Discovery", 1), 
	("GS", "100", "Career and Self Discovery", 1), 
	("GS", "102R", "Strategies Academic Success", 2), 
	("HCA", "285", "Intro to HCA", 3), 
	("HCA", "285", "Intro to HCA", 3), 
	("HEB", "101", "Biblical Hebrew I", 3), 
	("HIST", "104", "History Skills and Careers", 1), 
	("HIST", "104", "History Skills and Careers", 1), 
	("HIST", "104", "History Skills and Careers", 1), 
	("HIST", "115", "History and Civics for El Ed", 2), 
	("HIST", "115", "History and Civics for El Ed", 2), 
	("HIST", "120", "U.S. History to 1877", 3), 
	("HIST", "120", "U.S. History to 1877", 3), 
	("HIST", "120", "U.S. History to 1877", 3), 
	("HIST", "120", "U.S. History to 1877", 3), 
	("HIST", "121", "U.S. History Since 1877", 3), 
	("HIST", "121", "U.S. History Since 1877", 3), 
	("HIST", "121", "U.S. History Since 1877", 3), 
	("HIST", "121", "U.S. History Since 1877", 3), 
	("HIST", "201", "World History to 1500", 3), 
	("HIST", "201", "World History to 1500", 3), 
	("HIST", "201", "World History to 1500", 3), 
	("HIST", "201", "World History to 1500", 3), 
	("HIST", "202", "Modern World History", 3), 
	("HIST", "202", "Modern World History", 3), 
	("HIST", "202", "Modern World History", 3), 
	("HIST", "202", "Modern World History", 3), 
	("HORT", "224", "Introductory Plant ID", 2), 
	("HORT", "230", "Intro Landscape/Arch/Design", 3), 
	("HORT", "235", "Floral Design", 3), 
	("HORT", "235", "Floral Design", 3), 
	("HORT", "235", "Floral Design", 3), 
	("HORT", "277R", "Practicum Landscape Mgmt", 1), 
	("HORT", "287R", "Practicum in Floral Design", 1), 
	("HORT", "297R", "Practicum in Plant Shop", 1), 
	("HUM", "110", "Discovery Through the Arts", 3), 
	("HUM", "110", "Discovery Through the Arts", 3), 
	("HUM", "110", "Discovery Through the Arts", 3), 
	("HUM", "110", "Discovery Through the Arts", 3), 
	("HUM", "110", "Discovery Through the Arts", 3), 
	("HUM", "110", "Discovery Through the Arts", 3), 
	("HUM", "110", "Discovery Through the Arts", 3), 
	("HUM", "110", "Discovery Through the Arts", 3), 
	("HUM", "110", "Discovery Through the Arts", 3), 
	("HUM", "110", "Discovery Through the Arts", 3), 
	("HUM", "201", "Search Meaning Ancient World", 3), 
	("HUM", "201", "Search Meaning Ancient World", 3), 
	("HUM", "202", "Search Meaning Modern World", 3), 
	("HUM", "202", "Search Meaning Modern World", 3), 
	("HUM", "214", "Modern Arts and Propaganda", 3), 
	("IDS", "101", "Intro to Interdisc. Studies", 3), 
	("IDS", "101", "Intro to Interdisc. Studies", 3), 
	("IDS", "290R", "Special Topics", 1), 
	("INTST", "100", "Intro to Int'l Studies", 1), 
	("ITM", "101", "Intro to Cloud Technologies", 2), 
	("ITM", "101", "Intro to Cloud Technologies", 2), 
	("ITM", "101", "Intro to Cloud Technologies", 2), 
	("ITM", "111", "Introduction to Databases", 3), 
	("ITM", "111", "Introduction to Databases", 3), 
	("ITM", "111", "Introduction to Databases", 3), 
	("ITM", "112", "Intro to Linux", 2), 
	("ITM", "112", "Intro to Linux", 2), 
	("ITM", "220", "SQL", 3), 
	("ITM", "220", "SQL", 3), 
	("ITM", "220", "SQL", 3), 
	("ITM", "220", "SQL", 3), 
	("ITM", "220", "SQL", 3), 
	("LATIN", "101", "Latin I", 4), 
	("MATH", "100A", "Arithmetic", 3), 
	("MATH", "100B", "Beginning Algebra", 3), 
	("MATH", "100B", "Beginning Algebra", 3), 
	("MATH", "100B", "Beginning Algebra", 3), 
	("MATH", "100B", "Beginning Algebra", 3), 
	("MATH", "100B", "Beginning Algebra", 3), 
	("MATH", "100B", "Beginning Algebra", 3), 
	("MATH", "100B", "Beginning Algebra", 3), 
	("MATH", "100B", "Beginning Algebra", 3), 
	("MATH", "100B", "Beginning Algebra", 3), 
	("MATH", "100B", "Beginning Algebra", 3), 
	("MATH", "100B", "Beginning Algebra", 3), 
	("MATH", "101", "Intermediate Algebra", 4), 
	("MATH", "101", "Intermediate Algebra", 4), 
	("MATH", "101", "Intermediate Algebra", 4), 
	("MATH", "101", "Intermediate Algebra", 4), 
	("MATH", "101", "Intermediate Algebra", 4), 
	("MATH", "101", "Intermediate Algebra", 4), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108X", "Math for the Real World", 3), 
	("MATH", "108Y", "Real World Math with Support", 4), 
	("MATH", "108Y", "Real World Math with Support", 4), 
	("MATH", "109", "Precalculus", 5), 
	("MATH", "109", "Precalculus", 5), 
	("MATH", "109", "Precalculus", 5), 
	("MATH", "109", "Precalculus", 5), 
	("MATH", "110X", "College Algebra", 3), 
	("MATH", "110X", "College Algebra", 3), 
	("MATH", "110X", "College Algebra", 3), 
	("MATH", "110X", "College Algebra", 3), 
	("MATH", "110X", "College Algebra", 3), 
	("MATH", "111", "Trigonometry", 2), 
	("MATH", "112X", "Calculus I", 4), 
	("MATH", "112X", "Calculus I", 4), 
	("MATH", "112X", "Calculus I", 4), 
	("MATH", "112X", "Calculus I", 4), 
	("MATH", "112X", "Calculus I", 4), 
	("MATH", "112X", "Calculus I", 4), 
	("MATH", "113", "Calculus II", 3), 
	("MATH", "113", "Calculus II", 3), 
	("MATH", "119", "App Calculus for Data Analy", 4), 
	("MATH", "190", "Tutoring Mathematics", 1), 
	("MATH", "205", "Math Reasoning Teachers 1", 3), 
	("MATH", "205", "Math Reasoning Teachers 1", 3), 
	("MATH", "205", "Math Reasoning Teachers 1", 3), 
	("MATH", "206", "Math Reasoning Teachers 2", 2), 
	("MATH", "206", "Math Reasoning Teachers 2", 2), 
	("MATH", "214", "Multivariable/Vector Calc", 3), 
	("MATH", "214", "Multivariable/Vector Calc", 3), 
	("MATH", "214E", "Teaching Calculus", 1), 
	("MATH", "215", "Multivariable Calculus", 4), 
	("MATH", "215", "Multivariable Calculus", 4), 
	("MATH", "221A", "Business Statistics", 3), 
	("MATH", "221A", "Business Statistics", 3), 
	("MATH", "221A", "Business Statistics", 3), 
	("MATH", "221A", "Business Statistics", 3), 
	("MATH", "221A", "Business Statistics", 3), 
	("MATH", "221A", "Business Statistics", 3), 
	("MATH", "221B", "Biostatistics", 3), 
	("MATH", "221B", "Biostatistics", 3), 
	("MATH", "221B", "Biostatistics", 3), 
	("MATH", "221B", "Biostatistics", 3), 
	("MATH", "221B", "Biostatistics", 3), 
	("MATH", "221B", "Biostatistics", 3), 
	("MATH", "221C", "Social Science Statistics", 3), 
	("MATH", "221C", "Social Science Statistics", 3), 
	("MATH", "221C", "Social Science Statistics", 3), 
	("MATH", "221C", "Social Science Statistics", 3), 
	("MATH", "221D", "Intro Statistics with R", 3), 
	("MATH", "221D", "Intro Statistics with R", 3), 
	("MATH", "241", "Fundamentals Linear Algebra", 2), 
	("MATH", "275", "Math Connections Teachers", 3), 
	("MATH", "280", "Problem Solving", 3), 
	("MATH", "283", "Modeling with Probability", 2), 
	("MATH", "295R", "Special Topics in Math", 1), 
	("MATH", "295R", "Special Topics in Math", 1), 
	("MATH", "295R", "Special Topics in Math", 1), 
	("ME", "101", "Intro Engineering/Technology", 1), 
	("ME", "101", "Intro Engineering/Technology", 1), 
	("ME", "101", "Intro Engineering/Technology", 1), 
	("ME", "142", "Engineering Computation", 3), 
	("ME", "142", "Engineering Computation", 3), 
	("ME", "162", "Fundamentals in 2D CADD", 3), 
	("ME", "172", "Parametric Mechanical CAD", 3), 
	("ME", "172", "Parametric Mechanical CAD", 3), 
	("ME", "172", "Parametric Mechanical CAD", 3), 
	("ME", "201", "Engineering Mech: Statics", 3), 
	("ME", "201", "Engineering Mech: Statics", 3), 
	("ME", "202", "Strength of Materials", 3), 
	("ME", "202", "Strength of Materials", 3), 
	("ME", "204", "Dynamics", 3), 
	("ME", "204", "Dynamics", 3), 
	("ME", "250", "Materials Science", 3), 
	("ME", "280", "Mechanical Design I", 3), 
	("MET", "231", "Mfg. Processes I", 2), 
	("MET", "231", "Mfg. Processes I", 2), 
	("MET", "231L", "Mfg. Processes I Lab", 1), 
	("MET", "231L", "Mfg. Processes I Lab", 1), 
	("MET", "231L", "Mfg. Processes I Lab", 1), 
	("MET", "231L", "Mfg. Processes I Lab", 1), 
	("MET", "231L", "Mfg. Processes I Lab", 1), 
	("MET", "231L", "Mfg. Processes I Lab", 1), 
	("MET", "250L", "Materials Lab", 1), 
	("MKT", "100", "Careers in Marketing", 1), 
	("MKT", "100", "Careers in Marketing", 1), 
	("MKT", "100", "Careers in Marketing", 1), 
	("MKT", "100", "Careers in Marketing", 1), 
	("MS", "101", "Leadership/Personal Dev", 3), 
	("MS", "101S", "Ldrshp / Pers Dev - Lecture", 1), 
	("MS", "102", "Foundations in Leadership", 3), 
	("MS", "102S", "Fndatns in Ldrshp - Lecture", 1), 
	("MUSIC", "101", "Music and the Humanities", 3), 
	("MUSIC", "101", "Music and the Humanities", 3), 
	("MUSIC", "101", "Music and the Humanities", 3), 
	("MUSIC", "102", "Music Western Civilization", 3), 
	("MUSIC", "104", "Group Vocal Instruction", 2), 
	("MUSIC", "104", "Group Vocal Instruction", 2), 
	("MUSIC", "104", "Group Vocal Instruction", 2), 
	("MUSIC", "104", "Group Vocal Instruction", 2), 
	("MUSIC", "105", "Class Piano Instruction I", 2), 
	("MUSIC", "105", "Class Piano Instruction I", 2), 
	("MUSIC", "105", "Class Piano Instruction I", 2), 
	("MUSIC", "105", "Class Piano Instruction I", 2), 
	("MUSIC", "106", "Group Organ Instruction", 2), 
	("MUSIC", "107", "Class Piano Instruction II", 2), 
	("MUSIC", "107", "Class Piano Instruction II", 2), 
	("MUSIC", "109", "Group Guitar Instruction I", 2), 
	("MUSIC", "109", "Group Guitar Instruction I", 2), 
	("MUSIC", "109", "Group Guitar Instruction I", 2), 
	("MUSIC", "130", "Practical Musicianship", 3), 
	("MUSIC", "155", "Intro to Vocal Methods", 2), 
	("MUSIC", "156", "Basic Piano", 2), 
	("MUSIC", "158A", "Piano Lessons", 1), 
	("MUSIC", "158B", "Organ Lessons", 1), 
	("MUSIC", "158C", "Harp Lessons", 1), 
	("MUSIC", "158D", "Voice Lessons", 1), 
	("MUSIC", "158E", "Violin Lessons", 1), 
	("MUSIC", "158F", "Viola Lessons", 1), 
	("MUSIC", "158G", "Cello Lessons", 1), 
	("MUSIC", "158H", "String Bass Lessons", 1), 
	("MUSIC", "158J", "Flute Lessons", 1), 
	("MUSIC", "158K", "Oboe Lessons", 1), 
	("MUSIC", "158L", "Bassoon Lessons", 1), 
	("MUSIC", "158M", "Clarinet Lessons", 1), 
	("MUSIC", "158O", "Trumpet Lessons", 1), 
	("MUSIC", "158P", "French Horn Lessons", 1), 
	("MUSIC", "158Q", "Trombone Lessons", 1), 
	("MUSIC", "158R", "Euphonium Lessons", 1), 
	("MUSIC", "158S", "Tuba Lessons", 1), 
	("MUSIC", "158T", "Percussion Lessons", 1), 
	("MUSIC", "158V", "Composition Lessons", 1), 
	("MUSIC", "158Z", "Jazz Piano Lessons", 1), 
	("MUSIC", "160A", "Piano Lessons - I", 2), 
	("MUSIC", "160B", "Organ Lessons - I", 2), 
	("MUSIC", "160C", "Harp Lessons - I", 2), 
	("MUSIC", "160E", "Violin Lessons - I", 2), 
	("MUSIC", "160F", "Viola Lessons I", 2), 
	("MUSIC", "160G", "Cello Lessons I", 2), 
	("MUSIC", "160H", "String Bass Lessons - I", 2), 
	("MUSIC", "160J", "Flute Lessons - I", 1), 
	("MUSIC", "160K", "Oboe Lessons - I", 1), 
	("MUSIC", "160L", "Bassoon Lessons - I", 1), 
	("MUSIC", "160M", "Clarinet Lessons - I", 1), 
	("MUSIC", "160N", "Saxophone Lessons - I", 1), 
	("MUSIC", "160P", "French Horn Lessons I", 1), 
	("MUSIC", "160Q", "Trombone Lessons - I", 1), 
	("MUSIC", "160R", "Euphonium Lessons - I", 1), 
	("MUSIC", "160S", "Tuba Lessons - I", 1), 
	("MUSIC", "160T", "Percussion Lessons - I", 1), 
	("MUSIC", "160Z", "Jazz Piano Lessons - I", 2), 
	("MUSIC", "161A", "Piano Lessons - II", 2), 
	("MUSIC", "161B", "Organ Lessons - II", 2), 
	("MUSIC", "161C", "Harp Lessons - II", 2), 
	("MUSIC", "161D", "Voice Lessons - II", 2), 
	("MUSIC", "161E", "Violin Lessons - II", 2), 
	("MUSIC", "161F", "Viola Lessons - II", 2), 
	("MUSIC", "161G", "Cello Lessons - II", 2), 
	("MUSIC", "161H", "String Bass Lessons - II", 2), 
	("MUSIC", "161J", "Flute Lessons - II", 1), 
	("MUSIC", "161M", "Clarinet Lessons - II", 1), 
	("MUSIC", "161N", "Saxophone Lessons - II", 1), 
	("MUSIC", "161O", "Trumpet Lessons - II", 1), 
	("MUSIC", "161P", "French Horn Lessons - II", 1), 
	("MUSIC", "161Q", "Trombone Lessons - II", 1), 
	("MUSIC", "161R", "Euphonium Lessons - II", 1), 
	("MUSIC", "161S", "Tuba Lessons - II", 1), 
	("MUSIC", "161T", "Percussion Lessons - II", 1), 
	("MUSIC", "161Z", "Jazz Piano Lessons - II", 2), 
	("MUSIC", "165A", "Diction for Singers I", 2), 
	("MUSIC", "165B", "Diction for Singers II", 2), 
	("MUSIC", "172", "Musicianship 1", 3), 
	("MUSIC", "172", "Musicianship 1", 3), 
	("MUSIC", "209", "Music Technology", 1), 
	("MUSIC", "209", "Music Technology", 1), 
	("MUSIC", "212", "Musicianship 3", 3), 
	("MUSIC", "213", "Musicianship 4", 3), 
	("MUSIC", "256", "Piano Skills", 1), 
	("MUSIC", "260A", "Piano Lessons - III", 2), 
	("MUSIC", "260B", "Organ Lessons - III", 2), 
	("MUSIC", "260C", "Harp Lessons - III", 2), 
	("MUSIC", "260D", "Voice Lessons - III", 2), 
	("MUSIC", "260E", "Violin Lessons - III", 2), 
	("MUSIC", "260F", "Viola Lessons - III", 2), 
	("MUSIC", "260G", "Cello Lessons - III", 2), 
	("MUSIC", "260H", "String Bass Lessons - III", 2), 
	("MUSIC", "260J", "Flute Lessons - III", 2), 
	("MUSIC", "260K", "Oboe Lessons - III", 2), 
	("MUSIC", "260L", "Bassoon Lessons - III", 2), 
	("MUSIC", "260M", "Clarinet Lessons - III", 2), 
	("MUSIC", "260N", "Saxophone Lessons - III", 2), 
	("MUSIC", "260O", "Trumpet Lessons - III", 2), 
	("MUSIC", "260P", "French Horn Lessons - III", 2), 
	("MUSIC", "260Q", "Trombone Lessons - III", 2), 
	("MUSIC", "260R", "Euphonium Lessons - III", 2), 
	("MUSIC", "260S", "Tuba Lessons - III", 2), 
	("MUSIC", "260T", "Percussion Lessons - III", 2), 
	("MUSIC", "260Z", "Jazz Piano Lessons III", 2), 
	("MUSIC", "261A", "Piano IV Lessons", 2), 
	("MUSIC", "261B", "Organ IV Lessons", 2), 
	("MUSIC", "261C", "Harp IV Lessons", 2), 
	("MUSIC", "261D", "Voice IV Lessons", 2), 
	("MUSIC", "261E", "Violin Lessons - IV", 2), 
	("MUSIC", "261F", "Viola Lessons - IV", 2), 
	("MUSIC", "261G", "Cello IV Lessons", 2), 
	("MUSIC", "261H", "String Bass Lessons - IV", 2), 
	("MUSIC", "261J", "Flute Lessons - IV", 2), 
	("MUSIC", "261K", "Oboe Lessons - IV", 2), 
	("MUSIC", "261L", "Bassoon Lessons - IV", 2), 
	("MUSIC", "261M", "Clarinet Lessons - IV", 2), 
	("MUSIC", "261N", "Saxophone Lessons - IV", 2), 
	("MUSIC", "261O", "Trumpet IV Lessons", 2), 
	("MUSIC", "261Q", "Trombone Lessons - IV", 2), 
	("MUSIC", "261R", "Euphonium IV Lessons", 2), 
	("MUSIC", "261S", "Tuba Lessons - IV", 2), 
	("MUSIC", "261T", "Percussion Lessons - IV", 2), 
	("MUSIC", "261Z", "Jazz Piano Lessons - IV", 2), 
	("MUSIC", "265", "Piano Teaching I", 2), 
	("MUSIC", "270", "Elem Methods Music Majors", 2), 
	("MUSIC", "299", "Basic Audio Engineering", 2), 
	("NURS", "105", "Introduction to Nursing", 1), 
	("NURS", "105", "Introduction to Nursing", 1), 
	("NURS", "105", "Introduction to Nursing", 1), 
	("NURS", "105", "Introduction to Nursing", 1), 
	("NURS", "105", "Introduction to Nursing", 1), 
	("NURS", "105", "Introduction to Nursing", 1), 
	("NURS", "295", "Pharmacology", 2), 
	("NURS", "295", "Pharmacology", 2), 
	("NURSF", "110", "Pregnancy", 1), 
	("NURSF", "110", "Pregnancy", 1), 
	("NUTR", "110", "Intro to Human Nutrition", 3), 
	("NUTR", "120", "Intro to Dietetics", 1), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "150", "Human Nutrition Essentials", 3), 
	("NUTR", "200", "Nutrient Metabolism", 3), 
	("PEACE", "101", "Conflict and Peace", 3), 
	("PEACE", "101", "Conflict and Peace", 3), 
	("PEACE", "101", "Conflict and Peace", 3), 
	("PH", "101", "Fundamentals of Physics", 3), 
	("PH", "101", "Fundamentals of Physics", 3), 
	("PH", "101", "Fundamentals of Physics", 3), 
	("PH", "105", "Intro Applied Physics I", 4), 
	("PH", "105", "Intro Applied Physics I", 4), 
	("PH", "106", "Intro Applied Physics II", 4), 
	("PH", "106", "Intro Applied Physics II", 4), 
	("PH", "121", "Principles of Physics I", 3), 
	("PH", "121", "Principles of Physics I", 3), 
	("PH", "121", "Principles of Physics I", 3), 
	("PH", "121", "Principles of Physics I", 3), 
	("PH", "121", "Principles of Physics I", 3), 
	("PH", "121", "Principles of Physics I", 3), 
	("PH", "123", "Principles of Physics II", 3), 
	("PH", "123", "Principles of Physics II", 3), 
	("PH", "123", "Principles of Physics II", 3), 
	("PH", "127", "Introduction to Astronomy", 3), 
	("PH", "135", "Intro Scientific Computing", 2), 
	("PH", "150", "Beginning Physics Lab", 1), 
	("PH", "150", "Beginning Physics Lab", 1), 
	("PH", "220", "Principles of Physics III", 3), 
	("PH", "220", "Principles of Physics III", 3), 
	("PH", "223", "Engineering Physics", 4), 
	("PH", "250", "Intermediate Physics Lab", 1), 
	("PH", "279", "Modern Physics", 3), 
	("PH", "295", "Math/Computational Physics", 3), 
	("PHIL", "110", "The Search for Wisdom", 3), 
	("PHIL", "110", "The Search for Wisdom", 3), 
	("PHIL", "110", "The Search for Wisdom", 3), 
	("PHIL", "201", "Ancient/Medieval Philosophy", 3), 
	("PHIL", "205", "Logic and Critical Thinking", 3), 
	("POLSC", "100", "Intro to Political Science", 1), 
	("POLSC", "110", "American Government", 3), 
	("POLSC", "110", "American Government", 3), 
	("POLSC", "110", "American Government", 3), 
	("POLSC", "150", "Intro Comparative Politics", 3), 
	("POLSC", "150", "Intro Comparative Politics", 3), 
	("POLSC", "170", "International Politics", 3), 
	("POLSC", "170", "International Politics", 3), 
	("POLSC", "200", "Research Methods", 3), 
	("POLSC", "200", "Research Methods", 3), 
	("PSYCH", "111", "General Psychology", 3), 
	("PSYCH", "111", "General Psychology", 3), 
	("PSYCH", "111", "General Psychology", 3), 
	("PSYCH", "111", "General Psychology", 3), 
	("PSYCH", "111", "General Psychology", 3), 
	("PSYCH", "111", "General Psychology", 3), 
	("PSYCH", "111", "General Psychology", 3), 
	("PSYCH", "111", "General Psychology", 3), 
	("PSYCH", "201", "Developmental Psych Lifespan", 3), 
	("PSYCH", "201", "Developmental Psych Lifespan", 3), 
	("PSYCH", "201", "Developmental Psych Lifespan", 3), 
	("PSYCH", "201", "Developmental Psych Lifespan", 3), 
	("PSYCH", "201", "Developmental Psych Lifespan", 3), 
	("PTA", "205", "Therapeutic Procedures 2", 4), 
	("PTA", "210", "Clinical Pathology", 3), 
	("PTA", "220", "Principles of Rehabilitation", 3), 
	("PTA", "221", "Pediatrics for the PTA", 1), 
	("PTA", "299", "Seminar", 1), 
	("PUBH", "100", "Exp Careers in Hlth Svs", 1), 
	("PUBH", "132", "Personal Health & Wellness", 3), 
	("PUBH", "132", "Personal Health & Wellness", 3), 
	("PUBH", "240", "Intro to Public Health", 2), 
	("REL", "100", "Intro Church of Jesus Christ", 2), 
	("REL", "121", "Book of Mormon", 2), 
	("REL", "121", "Book of Mormon", 2), 
	("REL", "121", "Book of Mormon", 2), 
	("REL", "121", "Book of Mormon", 2), 
	("REL", "121", "Book of Mormon", 2), 
	("REL", "122", "Book of Mormon", 2), 
	("REL", "122", "Book of Mormon", 2), 
	("REL", "122", "Book of Mormon", 2), 
	("REL", "130", "Missionary Preparation", 2), 
	("REL", "130", "Missionary Preparation", 2), 
	("REL", "130", "Missionary Preparation", 2), 
	("REL", "130", "Missionary Preparation", 2), 
	("REL", "130", "Missionary Preparation", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "200C", "The Eternal Family", 2), 
	("REL", "211", "New Testament", 2), 
	("REL", "211", "New Testament", 2), 
	("REL", "211", "New Testament", 2), 
	("REL", "211", "New Testament", 2), 
	("REL", "211", "New Testament", 2), 
	("REL", "212", "New Testament", 2), 
	("REL", "212", "New Testament", 2), 
	("REL", "212", "New Testament", 2), 
	("REL", "212", "New Testament", 2), 
	("REL", "215", "Scripture Study", 2), 
	("REL", "215", "Scripture Study", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "225C", "Foundations of Restoration", 2), 
	("REL", "234", "Prep for Eternal Marriage", 2), 
	("REL", "234", "Prep for Eternal Marriage", 2), 
	("REL", "234", "Prep for Eternal Marriage", 2), 
	("REL", "234", "Prep for Eternal Marriage", 2), 
	("REL", "234", "Prep for Eternal Marriage", 2), 
	("REL", "235", "Building an Eternal Marriage", 2), 
	("REL", "235", "Building an Eternal Marriage", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "250C", "Jesus Christ Evrlst Gospel", 2), 
	("REL", "261", "Intro Temple & Family Hist.", 2), 
	("REL", "261", "Intro Temple & Family Hist.", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("REL", "275C", "Teachings of Book of Mormon", 2), 
	("RM", "100", "Rec Management Orientation", 2), 
	("RM", "100", "Rec Management Orientation", 2), 
	("RM", "123", "Basic Outdoor Skills", 2), 
	("RM", "123", "Basic Outdoor Skills", 2), 
	("RM", "123", "Basic Outdoor Skills", 2), 
	("RM", "200", "Leadership", 3), 
	("RM", "220", "Outdoor Leadership Seminar", 3), 
	("RM", "223", "Wilderness First Aid", 3), 
	("RM", "223", "Wilderness First Aid", 3), 
	("RM", "223C", "Traditional Camping", 2), 
	("RM", "223F", "Rock Climbing", 2), 
	("RM", "223G", "Mountaineering", 4), 
	("RM", "223K", "Outdoor Cooking", 2), 
	("RM", "223K", "Outdoor Cooking", 2), 
	("RM", "224A", "Fly Tying", 2), 
	("RM", "224C", "Canoeing", 2), 
	("RM", "270", "Intro Therapeutic Recreation", 3), 
	("RUSS", "102", "Beginning Russian II", 4), 
	("RUSS", "201", "Intermediate Russian I", 4), 
	("SCIED", "259", "Integrated Science", 4), 
	("SOC", "111", "Introduction to Sociology", 3), 
	("SOC", "111", "Introduction to Sociology", 3), 
	("SOC", "111", "Introduction to Sociology", 3), 
	("SOC", "111", "Introduction to Sociology", 3), 
	("SOC", "111", "Introduction to Sociology", 3), 
	("SOC", "230", "Sociological Explorations", 3), 
	("SPAN", "101", "Beginning Spanish I", 4), 
	("SPAN", "101", "Beginning Spanish I", 4), 
	("SPAN", "101", "Beginning Spanish I", 4), 
	("SPAN", "101", "Beginning Spanish I", 4), 
	("SPAN", "101", "Beginning Spanish I", 4), 
	("SPAN", "101", "Beginning Spanish I", 4), 
	("SPAN", "102", "Beginning Spanish II", 4), 
	("SPAN", "201", "Intermediate Spanish", 4), 
	("SPAN", "202", "Readings Hispanic Literature", 3), 
	("SW", "101", "Social Work Freshman Seminar", 1), 
	("SW", "260", "Introduction to Social Work", 3), 
	("SW", "260", "Introduction to Social Work", 3), 
	("TA", "115", "Introduction to Theatre", 3), 
	("TA", "116", "Dramatic Structure/Analysis", 2), 
	("TA", "117", "Intro to Film Art/Analysis", 3), 
	("TA", "117", "Intro to Film Art/Analysis", 3), 
	("TA", "117", "Intro to Film Art/Analysis", 3), 
	("TA", "119", "Intro to Technical Theatre", 3), 
	("TA", "119", "Intro to Technical Theatre", 3), 
	("TA", "119", "Intro to Technical Theatre", 3), 
	("TA", "119", "Intro to Technical Theatre", 3), 
	("TA", "121", "Voice Diction", 2), 
	("TA", "121", "Voice Diction", 2), 
	("TA", "123M", "Acting I", 3), 
	("TA", "123M", "Acting I", 3), 
	("TA", "123W", "Acting I", 3), 
	("TA", "123W", "Acting I", 3), 
	("TA", "126", "Stage Makeup", 2), 
	("TA", "217", "Theatre Design Fundamentals", 2), 
	("TA", "223M", "Acting II", 3), 
	("TA", "223W", "Acting II", 3), 
	("TA", "233", "Movement for Theatre", 2), 
	("TESOL", "200", "Fundamentals of TESOL", 3), 
	("TESOL", "200", "Fundamentals of TESOL", 3), 
	("VDC", "120", "Intro to CAD", 3), 
	("VDC", "170", "Plan Reading", 1), 
	("VDC", "170", "Plan Reading", 1), 
	("VDC", "180", "Presentation Graphics I", 3), 
	("VDC", "180", "Presentation Graphics I", 3), 
	("VDC", "190", "Building Info Modeling I", 3), 
	("VDC", "190", "Building Info Modeling I", 3), 
	("VDC", "190", "Building Info Modeling I", 3), 
	("VDC", "290", "Building Info Modeling II", 3), 
	("WDD", "130", "Web Fundamentals", 2), 
	("WDD", "130", "Web Fundamentals", 2), 
	("WDD", "130", "Web Fundamentals", 2), 
	("WDD", "130", "Web Fundamentals", 2), 
	("WDD", "130", "Web Fundamentals", 2), 
	("WDD", "131", "Dynamic Web Fundamentals", 2), 
	("WDD", "131", "Dynamic Web Fundamentals", 2), 
	("WDD", "131", "Dynamic Web Fundamentals", 2), 
	("WDD", "199", "Technology Product Dev I", 2), 
	("WDD", "231", "Web Frontend Development I", 2), 
	("WDD", "299", "Technology Product Dev II", 2), 
	("WELD", "100", "Introduction to Welding", 1), 
	("WELD", "100", "Introduction to Welding", 1), 
	("WELD", "100", "Introduction to Welding", 1), 
	("WELD", "170", "Weld Sci & Allied Processes", 2), 
	("WELD", "170", "Weld Sci & Allied Processes", 2), 
	("WELD", "170L", "Weld Sci & Allied Proc Lab", 2), 
	("WELD", "170L", "Weld Sci & Allied Proc Lab", 2), 
	("WELD", "170L", "Weld Sci & Allied Proc Lab", 2), 
	("WELD", "224", "Welding Engineering I", 2), 
	("WELD", "224L", "Welding Engineering I Lab", 2), 
	("WELD", "243L", "Welding Engineering II Lab", 2)
);

insert into instructors (name) values
(
	('Abegglen, Joshua Ken'), 
	('Adams, Alyssa Brooke'), 
	('Adamson, Duane Allen'), 
	('Alba, Matthew Charles'), 
	('Allen, Charles Nathan'), 
	('Allen, David W.'), 
	('Allen, Joshua'), 
	('Alley, Lewis'), 
	('Allison, Chris M.'), 
	('Allphin, Andrew Nylen'), 
	('Allred, Isaac'), 
	('Allred, Jason Morgan'), 
	('Alvey, Zachariah J.'), 
	('Ames, Gary Adna'), 
	('Amidan, Brett'), 
	('Anderson, Joseph F.'), 
	('Anderson, Julie Ann'), 
	('Anderson, Mirinda L.'), 
	('Anderson, Stuart'), 
	('Anderson, Thomas Neal'), 
	('Andrews, Chris S.'), 
	('Angus, Gregory David'), 
	('Anyanwu, Maxwel Levi'), 
	('Armstrong, Bradley J.'), 
	('Ashby, David Keith'), 
	('Ashby, Eda'), 
	('Ashcraft, Carol'), 
	('Astel, Kirk A.'), 
	('Astel, Nathan'), 
	('Atkinson, Brian J.'), 
	('Atwood, Jason R.'), 
	('Austad, Jamie L.'), 
	('Austad, Jonathan A.'), 
	('Babcock, Matthew James'), 
	('Baeza, Amy N.'), 
	('Bagley, Eric Bruce'), 
	('Bagley, Lisa Nicole'), 
	('Bahr, Amelia'), 
	('Bailey, Caleb M.'), 
	('Bailey, Jeremy Robert'), 
	('Bair, Adam Ronald'), 
	('Baird, Daniel B.'), 
	('Baird, Gary I.'), 
	('Baird, Heather'), 
	('Baird, Sariah Marie'), 
	('Baker, Lanning R.'), 
	('Baldwin, Donald'), 
	('Baldwin, Hazen Kyle'), 
	('Baldwin, Thomas'), 
	('Ballard, Michael Jay'), 
	('Ballard, Thomas McNeil'), 
	('Ballif, Adam B.'), 
	('Ballif, Kristi'), 
	('Ballou, Kristin Jean'), 
	('Balmforth, Sandra'), 
	('Barker, Devan Lynn'), 
	('Barker, Heidi'), 
	('Barlow, Trinity B.'), 
	('Barnes, Daniel V.'), 
	('Barney, Lee S.'), 
	('Baron, Eric'), 
	('Barrus, David Rondo'), 
	('Barzee, Rex A.'), 
	('Bateman, Preston J'), 
	('Bates, Briana'), 
	('Bates, Byron Ray'), 
	('Bates, Justin Philip'), 
	('Baxter, Jennifer Dawson'), 
	('Bean, Brent Whiting'), 
	('Bean, Gaylynn'), 
	('Beard, Vanessa'), 
	('Beattie, Joshua'), 
	('Becerril-Garcia, Hector Alejandr'), 
	('Beebe, Amanda'), 
	('Belka, David Kenneth'), 
	('Benedict, Merle D.'), 
	('Benitez, Sandro Gaston'), 
	('Bennion, Erin'), 
	('Bennion, Mark Daniel'), 
	('Benson, Gary Charles'), 
	('Benson, Hyrum'), 
	('Billman, Eric J.'), 
	('Bingham, Donald P.'), 
	('Birch, Nathan'), 
	('Bird, Rebecca H.'), 
	('Bird, Robert R.'), 
	('Black, Kyle L.'), 
	('Blake, Julann W.'), 
	('Blakely, Teresa Blaser'), 
	('Blakeman, Jonathan William Leroy'), 
	('Blanchard, Carol M.'), 
	('Blanchard, Todd'), 
	('Bolingbroke, Michael K.'), 
	('Bone, Wendy Lyn'), 
	('Borup, Daniel'), 
	('Bourgeous, Keith Norman'), 
	('Bourgeous, Rachael P.'), 
	('Bowden, Jared N.'), 
	('Boyce, Christopher'), 
	('Bradshaw, Kevin'), 
	('Brailsford, Shanon'), 
	('Braun, Emily'), 
	('Bresee, Garrett J'), 
	('Briggs, Quinn'), 
	('Broadbent, Craig David'), 
	('Brooks, Cherri Holbrook'), 
	('Brooks, William Trevor'), 
	('Brower, Kevin L.'), 
	('Brower, Norette'), 
	('Brown, Brian L.'), 
	('Brown, Christine'), 
	('Brown, David E.'), 
	('Brown, Jason R.'), 
	('Brown, Tamara Lynne'), 
	('Brugger, William H.'), 
	('Brumbaugh, Lloyd'), 
	('Bryan, Christopher'), 
	('Bullard, Trulee Ann'), 
	('Bulloch, Lauren Alysse'), 
	('Burchfield, David'), 
	('Burgener, Kelly T.'), 
	('Burger, Andrew Edward'), 
	('Burnham, Nathan Garrett'), 
	('Burns, Robert B.'), 
	('Burton, Scott H.'), 
	('Busselberg, Paul'), 
	('Butcher, Ammon'), 
	('Butikofer, Sam Lorin'), 
	('Butterfield, Rex M.'), 
	('Bybee, Nolan John'), 
	('Call, Blaine Willard'), 
	('Call, Brian D.'), 
	('Call, Brittany Lynn'), 
	('Call, Stephenie'), 
	('Cameron, Gregory L.'), 
	('Cameron, Hilary A.'), 
	('Cameron, Scott C.'), 
	('Campbell, Donald Patrick'), 
	('Cannon, Paul'), 
	('Cardenas Melgar, Ana Cristina'), 
	('Carlos, Breanna Lee'), 
	('Carmack, Peter Legrand'), 
	('Carpenter, Anthony Robert'), 
	('Carpenter, Sharon'), 
	('Carr, Whitney Elizabeth'), 
	('Carter, Kelsie Chantelle'), 
	('Carter, Neal Alan'), 
	('Carter, Tate W.'), 
	('Castillow, Curtis Roy'), 
	('Castillow, Heather'), 
	('Castro, Fernando R.'), 
	('Cazier, Brielle Hammond'), 
	('Chandler, Curtis Steven'), 
	('Chapman, Denalee'), 
	('Chapman, Jeffery G.'), 
	('Chapman, John'), 
	('Chapman, Thomas G.'), 
	('Charrier, Alyssa'), 
	('Chavez, Lori Anne'), 
	('Chelson, Gary'), 
	('Christensen, Amanda N.'), 
	('Christensen, Brian Ralph'), 
	('Christensen, David Aaron'), 
	('Christensen, Heidi L.'), 
	('Christensen, James M'), 
	('Christensen, Kord'), 
	('Christopherson, Michael'), 
	('Christopherson, Michael'), 
	('Cisneros Lopez, Darlette'), 
	('Clark, Amy Joanne'), 
	('Clark, Brandon Marco'), 
	('Clark, Darren Phil'), 
	('Clark, Susan B.'), 
	('Clark, Tyler Chaz'), 
	('Clay, Samuel Lee,, II'), 
	('Clayton, Matthew'), 
	('Clayton, Robert William'), 
	('Clements, William Allred'), 
	('Clifford, Antonia L.'), 
	('Clifford, Richard J.'), 
	('Cloward, R. Dean'), 
	('Coates, Atina Marie'), 
	('Codling, Cory'), 
	('Coglianese, Mark Joseph'), 
	('Cole, Michael S.'), 
	('Coleman, James Dean'), 
	('Coleman, Robert Sean'), 
	('Coles, Kevin Douglas'), 
	('Collins, David C.'), 
	('Collins, Stephen Alan'), 
	('Colvin, Robert Lloyd'), 
	('Comeau, Luc V.'), 
	('Cook, Benjamin'), 
	('Cook, Kevin'), 
	('Cook, Kristie S'), 
	('Cooper, Cindy Taylor'), 
	('Cooper, Justin Teryl'), 
	('Cooper, Kevin'), 
	('Cordier, Westin Karl'), 
	('Cornick, Michael'), 
	('Cox, Paul Franklin'), 
	('Crandall, Kevin Don'), 
	('Cranmer, Jillisa'), 
	('Crawford, Elizabeth Marie'), 
	('Crawford, William C.,, III'), 
	('Crisp, Elizabeth E.'), 
	('Crisp, Ryan Patrick'), 
	('Critchlow, Tami Jean'), 
	('Cromar, Ryan D.'), 
	('Crosby, Sean Michael'), 
	('Crouch, Brian'), 
	('Crump, William Charles'), 
	('Cureton, Camille Westwood'), 
	('d\'Evegnee, Eric F.'), 
	('d\'Evegnee, Sarah H.'), 
	('Dabell, Ryan S.'), 
	('Dahlin, Madison'), 
	('Daines, Russell L.'), 
	('Datwyler, Richard F.'), 
	('Davis, Melinda M.'), 
	('Dayley, Glenn Hansen'), 
	('De Vera, Amy Anne'), 
	('Dean, Adam J'), 
	('DeLeeuw, William'), 
	('Delton, Yohan'), 
	('DeMordaunt, Amy'), 
	('Denning, William Matthew'), 
	('Dennis, Steven A.'), 
	('Dewall, K. Mark'), 
	('Dewall, Robyn'), 
	('Dewey, Daniel W.'), 
	('Diehl, Cody John'), 
	('Dietze-Hermosa, Martin Sterling'), 
	('Dillon, Kyle S.'), 
	('Dixon, Matthew'), 
	('Dorman, Brigham Taft'), 
	('Dorman, Jennifer'), 
	('Dorman, Shawn David'), 
	('Dotson, Brayden'), 
	('Douglass, Alison Brown'), 
	('Dredge, Bruce Matthew'), 
	('Dresen, Steven Paul'), 
	('Dukes, James Bradley'), 
	('Dummar, Dan C.'), 
	('Dummar, Rik Lee'), 
	('Duncan, Jesse S.'), 
	('Dunlop, Robin D McWhorter'), 
	('DUNN, ALEXIS'), 
	('DuPree, Devin'), 
	('Dupree, Kevin'), 
	('Duque, Lary N.'), 
	('Duque, Sharon W.'), 
	('Durfee, Anna'), 
	('Durfee, Arik'), 
	('Durfee, Rosemary'), 
	('Dustin, Tyler'), 
	('Eagar, R. Drew'), 
	('Earl, Rusty'), 
	('Eberhard, Jared'), 
	('Eckersell, Clair Bruce'), 
	('Edmonds, George Douglas'), 
	('Ekstrom, Levi'), 
	('Elison, Clint C.'), 
	('Ellingford, Justin'), 
	('Embree, Eric F.'), 
	('Empey, Cheryl Ann'), 
	('Evans, Kelly J.'), 
	('Faires, David Steven'), 
	('Farmer, Benjamin A.'), 
	('Farnsworth, Mark David'), 
	('Feik, Michael'), 
	('Feinberg, Krista R.'), 
	('Felt, Brian Earl'), 
	('Felts, Daniel W.'), 
	('Fife, McKay Scott'), 
	('Fisher, John Timothy'), 
	('Fisher, Mary J.'), 
	('Flora, Jason Dearden'), 
	('Flynn, Jason Scott'), 
	('Foushee, Brandon'), 
	('Foutz, Darryl H.'), 
	('Franson, Scott E.'), 
	('Frisby, Bernadette Marie'), 
	('Fuller, Jack Terrell'), 
	('Gahn, Forest James'), 
	('Galbraith, Kevin A.'), 
	('Galbraith, Kimball John'), 
	('Galbraith, Ninette A.'), 
	('Galer, Scott'), 
	('Galloway, Ruby'), 
	('Gardner, Ryan Scott'), 
	('Gardner, Samuel Rex'), 
	('Gardner, Scott Patrick'), 
	('Garner, Bradley Evan'), 
	('Garner, Carrie J.'), 
	('Gartside, James'), 
	('Gee, Eric Jerald'), 
	('Gentry, Michael S.'), 
	('George, Natalie'), 
	('George, Ryan'), 
	('Gibbons, Carl Robert'), 
	('Gibbons, Jessica Roderer'), 
	('Gifford, Kirk D.'), 
	('Gilbert, Janine'), 
	('Gleason, Benjamin Ivan'), 
	('Glenn, Kristen Dee'), 
	('Gneiting, Mikala'), 
	('Godderidge, Gary'), 
	('Godfrey, Kory Wendel'), 
	('Godfrey, Michael Kent'), 
	('Gomm, Christopher M'), 
	('Goodsell, Troy Larry'), 
	('Goodwill, Cynthia E.'), 
	('Goodwin, K. Shane'), 
	('Gordon, Misty'), 
	('Gorton, J. Terry'), 
	('Goude, Mallary'), 
	('Graham, Kaitlyn Clevenger'), 
	('Grant, C. Kendall'), 
	('Grant, Erin M'), 
	('Green, Holly V'), 
	('Green, Melissa'), 
	('Greenwood, Janell Dawn'), 
	('Griffin, Joseph Wyatt'), 
	('Griffin, Melissa'), 
	('Griffith, John S.'), 
	('Grimmett, Richard Ralph'), 
	('Grimshaw, Deborah'), 
	('Grover, Blake L.'), 
	('Grover, Quinn Kyle'), 
	('Gulbransen, Jeffrey'), 
	('Gunnerson, John'), 
	('Gwilliam, Ezra George'), 
	('Haacke, Spencer Leland'), 
	('Haderlie, Ehren F.'), 
	('Hales, Michael David'), 
	('Hales, Ryan Scott'), 
	('Hall, Andrew M'), 
	('Hamblin, Jeffrey Skip'), 
	('Hamilton, Blaine'), 
	('Hammond, Todd M.'), 
	('Hanks, Amy'), 
	('Hansen, Andra Kay'), 
	('Hansen, Dallin Richard'), 
	('Hansen, Donald'), 
	('Hansen, Evan D.'), 
	('Hansen, Kristi'), 
	('Hansen, Lisa Ann'), 
	('Hansen, Nels Edward'), 
	('Hansen, Ryan Franklin'), 
	('Harker, Ronald Brent'), 
	('Harper, Megan Elizabeth'), 
	('Harrell, David Reed'), 
	('Harrell, Jack A.'), 
	('Harrell, Rebecca'), 
	('Harris, Andrew Nathaniel'), 
	('Harris, Bryant Russell'), 
	('Harris, Jacqueline Haley'), 
	('Harris, Nathan J.'), 
	('Harris, Shaun'), 
	('Harrison, Aaron'), 
	('Hart, Stephanie'), 
	('Hatch, Daniel Patrick'), 
	('Hatch, Justin'), 
	('Hathaway, John E.'), 
	('Hatt, Richard A.'), 
	('Hawkes, Autumn Dawn'), 
	('Hawkins, Collin James'), 
	('Hayes, Adam R.'), 
	('Head, Samuel Lee'), 
	('Heap, Ryan'), 
	('Helfrich, James N.'), 
	('Helfrich, Rachel D.'), 
	('Hendershot, Shawnee Marie'), 
	('Henderson, Stephen C.'), 
	('Hendricks, Mary Lynette'), 
	('Hepner, Braden Ronald'), 
	('Hepworth, Natalia'), 
	('Hess, Terri L.'), 
	('Heuett, Kyle'), 
	('Heward, Aaron'), 
	('Heywood, Matthew Spencer'), 
	('Hibbard, Caroline R.'), 
	('Hibbard, John Dale'), 
	('Hiebert, Sarah'), 
	('Higginbotham, Holden R.'), 
	('Higgins, Derrel J.'), 
	('Higgins, Heidi J.'), 
	('Hildebrandt, Jay K.'), 
	('Hill, Benjamin Bruce'), 
	('Hill, Benjamin T.'), 
	('Hill, Joseph Dee'), 
	('Hillam, Todd'), 
	('Hirschi, Rick L.'), 
	('Hobbs, Anne Elizabeth'), 
	('Hobbs, Joshua T'), 
	('Hodges, DJ'), 
	('Hoffman, Joshua Daniel'), 
	('Holgate, Robert'), 
	('Hopkins, Diantha Smith'), 
	('Hopkins, Steven W.'), 
	('Hopla, Jim Joseph'), 
	('Horrocks, Kristina'), 
	('Howard, Brian R.'), 
	('Howard, Daris W.'), 
	('Howard, Jodi B.'), 
	('Howard, Kami Lee'), 
	('Howe, Timothy M'), 
	('Howe, Vanessa Rae Wright'), 
	('Huber, Kerry C.'), 
	('Hudman, Jaron'), 
	('Huff, Roy'), 
	('Huffaker, Stacey Ann'), 
	('Humphreys, Christopher D.'), 
	('Hunsaker, Steven Vaughn'), 
	('Hunt, Jason L.'), 
	('Hunt, Jason L.'), 
	('Hunt, Jason L.'), 
	('Hunter, Andrew'), 
	('Hunter, Christopher T.'), 
	('Hunter, Keegan F.'), 
	('Hunter, Stevan G.'), 
	('Hunter, Tatiana'), 
	('Huntsman, Ryan'), 
	('Huntsman, Wade D.'), 
	('Hurley, Casey Ann'), 
	('Hurst, Rachel K.'), 
	('Hurst, Scotty Joe'), 
	('Hyde, Andrew Orem'), 
	('Hymas, Bifid Euleza'), 
	('Isle, Brandon Willis'), 
	('Ivers, John J.'), 
	('Jack, Nathan'), 
	('Jack, Randall Vernon'), 
	('Jackson, Laurene S.'), 
	('Jenks, Kendra'), 
	('Jensen, Derek S.'), 
	('Jensen, Kendra'), 
	('Jensen, Shawn V.'), 
	('Jeppson, Alexandria Larke'), 
	('Jimison, Carla Louise'), 
	('Johansen, Shawn Peter'), 
	('Johanson, Paul T.'), 
	('Johansson, Emily Ada'), 
	('Johnsen, Stephanie'), 
	('Johnson, Bryanna'), 
	('Johnson, Craig A.'), 
	('Johnson, Dana A.'), 
	('Johnson, David Page'), 
	('Johnson, Jeffrey Kyle'), 
	('Johnson, Jon Paul'), 
	('Johnson, Katrina'), 
	('Johnson, Kaylie'), 
	('Johnson, Kirk C.'), 
	('Johnson, Melanie J'), 
	('Johnson, Nathan Brian'), 
	('Johnson, Roger Scott'), 
	('Johnson, Tricia Cox'), 
	('Jones, Jennifer'), 
	('Jones, Lisa F.'), 
	('Jordan, Scott'), 
	('Jorgensen, Molly'), 
	('Josephson, Theron M.'), 
	('Judkins, Joel D.'), 
	('Judy, Kayli'), 
	('Julander, Tahari Lane'), 
	('Kay, Aaron'), 
	('Keers, Christopher David'), 
	('Keller, Jay Rulon'), 
	('Keller, William Kody'), 
	('Kelley, Kevin'), 
	('Kelson, Todd'), 
	('Kempton, Randall S.'), 
	('Kennelly, Melanie D.'), 
	('Kerr, Cory Ryan'), 
	('Kerr, Daniel D.'), 
	('Kidd, Sheldon Arthur'), 
	('Killian, Shannon'), 
	('Kimball, Kevin C.'), 
	('Kimpel, Steven Scott'), 
	('Kinghorn, Brian Wayne'), 
	('Kinghorn, Kyle Brent'), 
	('Kinghorn, Malia'), 
	('Kinville, Kenneth'), 
	('Kinville, Ronald E.'), 
	('Kirby, Ellie'), 
	('Kirkham, Paulette E.'), 
	('Klein, Jon David'), 
	('Klingler, Greg Lyle'), 
	('Knapp, Ruth Ellen'), 
	('Knight, Michael'), 
	('Koetting, Kalvin Scott'), 
	('Kugath, Steven D.'), 
	('Kulis, Marcin'), 
	('Kunz, Suzette Gee'), 
	('Kunzler, Jayson Scott'), 
	('LaBaugh, Jack L.'), 
	('Lake, Warren'), 
	('Lamoreaux, Jeremy'), 
	('Landon, Becky Ann'), 
	('Larsen, Gary John'), 
	('Larsen, Melinda'), 
	('Lauder, Alexandra I'), 
	('Laughead, Michael Frederick'), 
	('Lawrence, Bradley W.'), 
	('Lawrence, James Jefferies'), 
	('Lawrence, Sheldon John'), 
	('Laws, Dru'), 
	('Leavenworth, Michael Israel'), 
	('Lecrone, Kristina Stone'), 
	('Lemon, Brian J.'), 
	('Lenhart, Michael'), 
	('Leukhardt, Joshua M'), 
	('Lewis, Bryan John'), 
	('Lewis, Hyrum Smith'), 
	('Lewis, John David'), 
	('Lewis, Kelley'), 
	('Lewis, Kiersten'), 
	('Lewis, Matthew J.'), 
	('Lindstrom, Craig Jay'), 
	('Lindstrom, John Nils'), 
	('Lines, Raymond T.'), 
	('Linford, Bret'), 
	('Llewellyn, Richard C.'), 
	('Llewellyn, Toni'), 
	('Loomis, Geoffrey William'), 
	('Lopez, Saul'), 
	('Lovell, Denice'), 
	('Lowe, Lauren'), 
	('Lowry, Christopher Miles'), 
	('Lucas, David Shannon'), 
	('Luke, Nadine Watson'), 
	('Lundin, William Kent'), 
	('Lupfer, Christopher'), 
	('Lybbert, Eric Conrad'), 
	('Ma, Martin'), 
	('Macbeth, Chad Nephi'), 
	('Macbeth, Natalie Dawn'), 
	('MacCabe, Jeff'), 
	('Madsen, Michael H.'), 
	('Magleby, David James'), 
	('Mahrt, Greg'), 
	('Manley, Matthew'), 
	('Manner, William Leslie'), 
	('Maroon, Mary'), 
	('Maroon, Matthew'), 
	('Marrott, Devon Courtney'), 
	('Marsden, Spencer'), 
	('Martin, Curtis Eli'), 
	('Martin, Holly'), 
	('Martin, Scott D.'), 
	('Matheson, Danielle M.'), 
	('Maughan, Justin D.'), 
	('Mawlam, Christian P.'), 
	('Mayberry, Cameron James'), 
	('McGary, Porter'), 
	('McKay, Trever B.'), 
	('McKee, Gregory'), 
	('McLane, Chad'), 
	('McLaughlin, Lisa'), 
	('McLaughlin, Michael J.'), 
	('McNeil, Stephen R.'), 
	('McNiven, Lisa'), 
	('McNiven, Tyler Scott'), 
	('McQuain, Betty H.'), 
	('McQuay, Alicia D.'), 
	('McQuay, Michael M.'), 
	('Meacham, Aaron Terry'), 
	('Meacham, Jamie'), 
	('Mecham, Bryce L.'), 
	('Mecham, Jessica F.'), 
	('Meeker, Nathan J.'), 
	('Melton, Greg L.'), 
	('Mema, Aubrie'), 
	('Mema, Medlir'), 
	('Memmott, Brian K.'), 
	('Merrill, Brian Leon'), 
	('Merrill, Darin A.'), 
	('Merrill, Katherine M.'), 
	('Merrill, Roger G.'), 
	('Meservy, Jeffrey D.'), 
	('Meyer, Kevin Thomas'), 
	('Miles, Matthew R.'), 
	('Miles, Sandra J.'), 
	('Miller, Aaron Nathaniel'), 
	('Miller, David Keith,, III'), 
	('Miller, Justin Ricks'), 
	('Mitchell, Nathan'), 
	('Moen, Joelle C.'), 
	('Moncayo, Daniel Andres'), 
	('Monette, Brandt Mason'), 
	('Moon, Bonnie S.'), 
	('Moore, Corey V.'), 
	('Moore, Matthew Michael'), 
	('Morley, Robert Brinton'), 
	('Morrell, Annette Anderson'), 
	('Morrill, Torrey Blayne'), 
	('Morring, Brent D.'), 
	('Morris, Jennifer'), 
	('Morris, Mark O.'), 
	('Moser, Kerry'), 
	('Moss, Jenifer'), 
	('Moss, Julie Lynn'), 
	('Moyle, Mark Wayne'), 
	('Muldowney, Ryan'), 
	('Mundt, Joel Brian'), 
	('Murdock, Jessica L.'), 
	('Murray, Brianna Hope'), 
	('NABAUM, ALEX'), 
	('Nance, Mark'), 
	('Neibaur, Jori Lyn'), 
	('Neimoyer, Susan'), 
	('Nelson, Abigail'), 
	('Nelson, Alicia'), 
	('Nelson, Curtis G.'), 
	('Nelson, Daren'), 
	('Nelson, Elizabeth'), 
	('Nelson, Janiel G.'), 
	('Nelson, Lance J.'), 
	('Nelson, Reese F.'), 
	('Newswander, Chad'), 
	('Newswander, Lynita'), 
	('Nielson, Joseph R.'), 
	('Nielson, Samuel Lynn'), 
	('Nilsson, Garrett B'), 
	('Nkala, Martin'), 
	('Nkala, Martin Takudzwa'), 
	('Nolte, Aimee'), 
	('Norris, Jaren Quinn'), 
	('Nuffer, Eileen Elizabeth'), 
	('Nygaard, Richard Jackson'), 
	('O\'Shaughnessy, Stephan J.'), 
	('Oberhansley, Kaisa Marie'), 
	('Okerlund, Micah Jo'), 
	('Oldroyd, Alisha Dawn'), 
	('Oliphant, David T.'), 
	('Oliphant, Eric'), 
	('Oliver, Jeffrey R.'), 
	('Olsen, David Karl'), 
	('Olsen, Kaelin M.'), 
	('Olsen, Trenton B.'), 
	('Orme, Heidi Dexter'), 
	('Orme, Kevin Cross'), 
	('Orme, Kristina Ann'), 
	('Orme, Susan Marla'), 
	('Owen, Deborah Julene'), 
	('Owen, Levi C.'), 
	('Pacini, Benjamin'), 
	('Pack, Jennifer'), 
	('Page, Brian Glenn'), 
	('Palmer, David'), 
	('Palmer, Jennifer'), 
	('Palmer, Katelynn'), 
	('Palmer, Sidney'), 
	('Papworth, Anne Hendricks'), 
	('Pardoe, Jennie'), 
	('Park, Emily Evangeline'), 
	('Parker, John S.'), 
	('Parker, Michelle M.'), 
	('Parker, Naomi'), 
	('Parker, Stephen S'), 
	('Parkinson, Rebecca'), 
	('Parson, Aaron'), 
	('Passey, Victoria'), 
	('Paul, Carly K.'), 
	('Paul, Michael A.'), 
	('Peck, David Raymond'), 
	('Peck, Emelyne'), 
	('Peeni, Bridget A.'), 
	('Pence, Benjamin'), 
	('Peterson, Jared'), 
	('Peterson, Kristy Anne'), 
	('Peterson, Nathan N.'), 
	('Phillips, Douglas Lee'), 
	('Phillips, Kenneth Nathan'), 
	('Pigott, David Allen'), 
	('Pires, Sergio Ricardo'), 
	('Pizzirani, Thiago'), 
	('Plass, Bryan William'), 
	('Platt, Jennifer'), 
	('Pollard, Virginia G'), 
	('Ponce, Sergio'), 
	('Poole, John A.'), 
	('Poole, Kuniko'), 
	('Pope, Bryan William'), 
	('Pope, Scott'), 
	('Potter, Delaney Marie'), 
	('Powell, Kerry L.'), 
	('Preator, Shawn Michael'), 
	('Pugh, Mark'), 
	('Pulsipher, Jeffry Ben'), 
	('Pulsipher, John David'), 
	('Pyper, Brian A.'), 
	('Pyper, Lon A.'), 
	('Qumsiyeh, Sahar B. H.'), 
	('Rademacher, Steven J.'), 
	('Radford, Wendie'), 
	('Radke-Moss, Andrea G.'), 
	('Rammell, Jason'), 
	('Randall, Shawn Richard'), 
	('Rarick, Timothy'), 
	('Rasmussen, Clay Louis'), 
	('Rasmussen, Sydnee Jain'), 
	('Ratcliffe, Gary C.'), 
	('Raya Lucero, Josue Jared'), 
	('Redder, Kyler J'), 
	('Reed, Ashley Nichole'), 
	('Reeder, Jason Robert'), 
	('Reyes, Enrique'), 
	('Reynolds, Alisa'), 
	('Reynolds, Morgen P.'), 
	('Rhien, Jedediah Whisler'), 
	('Rhoton, Derick W.'), 
	('Richards, Bruce Flint'), 
	('Richards, Debra'), 
	('Richards, James L.'), 
	('Richards, Jana'), 
	('Richey, Tyler'), 
	('Ricks, Cameron Jay'), 
	('Ricks, Danny Lynn'), 
	('Ricks, Melissa'), 
	('Ricks, Neal P.'), 
	('Ricks, Trevin'), 
	('Rigby, Steven E.'), 
	('Riggins, William J.'), 
	('Ririe, Seth Stephen'), 
	('Roberts, Kynda Harris'), 
	('Roberts, Paul K.'), 
	('Robertson, Lynette'), 
	('Robins, Cameron Keith'), 
	('Robins, Seth Lowell'), 
	('Robins, Tina'), 
	('Robinson, Jase Ryan'), 
	('Robinson, Melisa'), 
	('Robinson, Rebecca Joanna'), 
	('Robison, Katherine M.'), 
	('Rock, David Alan'), 
	('Rockwood, Perry'), 
	('Rockwood, Thomas'), 
	('Rogers, Olivia'), 
	('Rognon, James'), 
	('Romney, Nicole Cannariato'), 
	('Romney, Richard J.'), 
	('Romrell, Danae'), 
	('Rose, Jason D.'), 
	('Rose, Trent Michael'), 
	('Roth, Heidi'), 
	('Roth, Jennifer Albretsen'), 
	('Rowe, Brad James'), 
	('Rowe, David Allen'), 
	('Rowe, Trevor Ryan'), 
	('Rubert, Justin'), 
	('Ruebush, Rachel'), 
	('Ruebush, Shane S.'), 
	('Russell, Emily'), 
	('Russell, Melissa Sue'), 
	('Ryan, Rebekah'), 
	('Saathoff, Gordon Lee,, Jr.'), 
	('Sakota, Diedre'), 
	('Sanders, Bryan Patrick Mackenzie'), 
	('Sanders, Bryan Patrick Mackenzie '), 
	('Sanders, Rodney Lewis'), 
	('SANDERS, SKYLER'), 
	('Sargeant, Ryan R.'), 
	('Sauer, Cammie C.'), 
	('Saunders, Garrett H.'), 
	('Savage, Alexa Miller'), 
	('Savage, Tiffany Ann'), 
	('Schaat, Brian'), 
	('Schellenberg, Aaron T.'), 
	('Schellenberg, Adam N.'), 
	('Schmalle, Aaron Brent'), 
	('Schmid, Katherine T.'), 
	('Schmidt, Brent James'), 
	('Schmidt, Brian C.'), 
	('Scholes, Delaina M.'), 
	('Schroeder, Kirk'), 
	('Seamons, Rhonda'), 
	('Self, Juliann'), 
	('Sellers, Matthew David'), 
	('Sessions, Matthew'), 
	('Sessions, Michael Douglas'), 
	('Sexton, William Nelson'), 
	('Shaw, Jason Blaine'), 
	('Shaw, Lawrence Roy'), 
	('Shen, Lei'), 
	('Shippen, Trent W.'), 
	('Shoaf, Michael'), 
	('Simon, Tracie L.'), 
	('Singleton, Noelle'), 
	('Sinkovic, John,, III'), 
	('Sjoblom, Megan Pickard'), 
	('Skalski, Jonathan'), 
	('Slade, Jeremy Ryan'), 
	('Slagle, Jefferson D.'), 
	('Slagle, Julie'), 
	('Sloop, John Paul'), 
	('Smiley, Jess'), 
	('Smith, Aaron B.'), 
	('Smith, Cody Don'), 
	('Smith, Kevin Boyd'), 
	('Smith, Lindsay'), 
	('Smith, Megan'), 
	('Smith, Samuel Joseph Chester'), 
	('Smith, Stephen C.'), 
	('Smith, Travis S.'), 
	('Smoot, Lonna Joy'), 
	('Sorensen-Stowell, Kerensa Carlee'), 
	('Sorensen-Stowell'), 
	('Sorensen, Andrew'), 
	('Sorenson, Shayne'), 
	('Southwick, Hyrum Ephraim'), 
	('Spackman, Ross Arthur'), 
	('Spratling, Troy'), 
	('Squires, Trevor'), 
	('Squires, Trevor'), 
	('Staff (Art)'), 
	('Staff (AS)'), 
	('Staff (B)'), 
	('Staff (Chem)'), 
	('Staff (Comm)'), 
	('Staff (Faml)'), 
	('Staff (FIN)'), 
	('Staff (FL)'), 
	('Staff (Hum)'), 
	('Staff (MGMT)'), 
	('Staff (MKTG)'), 
	('Staff (Music)'), 
	('Staff (Psych)'), 
	('Staff (TA)'), 
	('Staff (TE)'), 
	('Staff2'), 
	('Staiger, Amy L.'), 
	('Stalker, Leslie Aaron'), 
	('Steenson, Tara B.'), 
	('Stephenson, Vaughn'), 
	('Stewart, Erin Marie Baker'), 
	('Stewart, Jared Scott'), 
	('Stewart, Robert C.'), 
	('Stewart, Steven J.'), 
	('Stock, Aspen'), 
	('Stohel, David W.'), 
	('Stoker, Daniel Wahlquist'), 
	('Stone, Kari Marie'), 
	('Storm, Ashley Rae'), 
	('Stratford, Abbey Grace'), 
	('Stratford, Charles'), 
	('Sturm, Dale Arthur'), 
	('Sturm, Valerie L.'), 
	('Summers, Michelle Illene'), 
	('Sunderland, Mary'), 
	('Swanson, Raymond B.'), 
	('Swenson, Jody A.'), 
	('Tanner, Tim Valison'), 
	('Taow, Sven D.'), 
	('Tate, Keaton'), 
	('Taylor, Alan M.'), 
	('Taylor, Angelina V.'), 
	('Taylor, Audrey Iris'), 
	('Taylor, Daniel'), 
	('Taylor, Marinda Judy'), 
	('Taylor, Matthew Aaron'), 
	('Taylor, Randon'), 
	('Teichert, David James'), 
	('Teichert, Kendall'), 
	('Terribilini, Michael'), 
	('Terry, Ryan Scott'), 
	('Teuscher, Jennifer'), 
	('Tew, Glade K.'), 
	('Thayne, Beth'), 
	('Thayne, Jeffrey'), 
	('Thiebaud, Robert'), 
	('Thomas, John Christian'), 
	('Thomas, Stephen Ricks'), 
	('Thomas, Susan'), 
	('Thompson, Alan'), 
	('Thompson, David Shane'), 
	('thompson, dustin john'), 
	('Thompson, Preston'), 
	('Thomson, Scott'), 
	('Thueson, Matthew'), 
	('Tibbitts, Joshua Cleve'), 
	('Tietjen, Robert'), 
	('Tippetts, Sean W.'), 
	('Toll, Jerry Allen'), 
	('Tollefson, Joshua Ethan'), 
	('Traynor, Ann Jensen'), 
	('Trimble, Jodene'), 
	('Trujillo, Caleb Michael'), 
	('Trujillo, Jonathan'), 
	('Tuck, Jared'), 
	('Tueller, Robert F.'), 
	('Turcotte, Stephen B.'), 
	('Turner, Heidi Jean'), 
	('Tuttle, Brian C.'), 
	('Twitchell, William James'), 
	('Ulrich, Patrick'), 
	('Vallejo, Ron'), 
	('Valora, Carrie Lynn'), 
	('Venema, Gregory A.'), 
	('Viana, Denise A'), 
	('Wach, Makayla'), 
	('Waddell, David Lynn'), 
	('Wagner, Elaine Rumsey'), 
	('Wahlen, Jessica'), 
	('Wahlquist, Robert F.'), 
	('Wakefield, Lyle'), 
	('Walburger, Allan Mark'), 
	('Waldron, Laryssa M'), 
	('Waldron, Thomas Loveless'), 
	('Walker, Celeste'), 
	('Walker, Jedd A.'), 
	('Walker, Juleen Anne'), 
	('Walker, Whitney Kaye'), 
	('Wall, Travis Gene'), 
	('Walsh, Emily'), 
	('Walsh, Patrick Edward'), 
	('Ward, Brady D.'), 
	('Ward, Kirk J.'), 
	('Ward, Linda Lee'), 
	('Ward, Susan C.'), 
	('Warnick, Shae'), 
	('Wasden, Shane T.'), 
	('Watkins, Angelia G.'), 
	('Watkins, Mark M.'), 
	('Watson, Lynn'), 
	('Watson, Tyler A.'), 
	('Wayne, Barbara Ann'), 
	('Webb, Matthew Michael'), 
	('Weber, Jonathan Craig'), 
	('Weber, Lana'), 
	('Weller, Gene S.'), 
	('Wells, Abigail Lawton'), 
	('Wells, Andrew Robert'), 
	('Wells, Brad'), 
	('Westover, Brenan'), 
	('Wheeler, Joshua Isaac'), 
	('Whiting, Adam'), 
	('Whiting, Jericho Condie'), 
	('Whiting, Richard M.'), 
	('Wiblin, Roger'), 
	('Wiggins, Bradford Jay'), 
	('Wilcox, Daniel Joseph'), 
	('Willden, Chase'), 
	('Williams, Christopher Glenn'), 
	('Williams, Greg K.'), 
	('Williams, Jared D.'), 
	('Williams, Jason R.'), 
	('Williams, Justin Lee'), 
	('Williams, Lane'), 
	('Williams, Michael D.'), 
	('Williams, Nathan H.'), 
	('Willis, Blake D.'), 
	('Willis, Debra Kaye'), 
	('Willis, Julie B.'), 
	('Willis, Steven K.'), 
	('Wilson, Andrew'), 
	('Wilson, Chris M.'), 
	('Wilson, Gregory Kent'), 
	('Wilson, MaryAnne'), 
	('Wilson, Robert'), 
	('Windous, Zachary Dell'), 
	('Winfree, Geoffrey R.'), 
	('Winiecke, Sarah'), 
	('Winiecke, Tyler'), 
	('Winkel, Steven A.'), 
	('Wise, Nathan Robert'), 
	('Wohlgemuth, Daniel Stewart'), 
	('Wolfley, Matthew Paul'), 
	('Woodbury, Caleb Andrew'), 
	('Woodfield, Bryce Sheffer'), 
	('Woodruff, Benjamin M.'), 
	('Woodward, Scott'), 
	('Worthen, Kevin Darrell'), 
	('Wray, Dwight Davis'), 
	('Wray, Grover Louis'), 
	('Wright, Robert Randon'), 
	('Yearsley, Matthew L.'), 
	('Yost, Tyson J.'), 
	('Zachreson, Matthew Ryan'), 
	('Zenger, Abby W.'), 
	('Zenger, John Thomas'), 
	('Zenger, Noelle Verna')
);

